/*
Immich

Immich API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type DuplicatesAPI interface {

	/*
	DeleteDuplicate Dismiss a duplicate group

	Dismiss a duplicate group by its ID, unlinking all assets in the group without deleting them.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return ApiDeleteDuplicateRequest
	*/
	DeleteDuplicate(ctx context.Context, id string) ApiDeleteDuplicateRequest

	// DeleteDuplicateExecute executes the request
	DeleteDuplicateExecute(r ApiDeleteDuplicateRequest) (*http.Response, error)

	/*
	DeleteDuplicates Delete duplicates

	Delete multiple duplicate assets specified by their IDs.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiDeleteDuplicatesRequest
	*/
	DeleteDuplicates(ctx context.Context) ApiDeleteDuplicatesRequest

	// DeleteDuplicatesExecute executes the request
	DeleteDuplicatesExecute(r ApiDeleteDuplicatesRequest) (*http.Response, error)

	/*
	GetAssetDuplicates Retrieve duplicates

	Retrieve a list of duplicate assets available to the authenticated user.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetAssetDuplicatesRequest
	*/
	GetAssetDuplicates(ctx context.Context) ApiGetAssetDuplicatesRequest

	// GetAssetDuplicatesExecute executes the request
	//  @return []DuplicateResponseDto
	GetAssetDuplicatesExecute(r ApiGetAssetDuplicatesRequest) ([]DuplicateResponseDto, *http.Response, error)

	/*
	ResolveDuplicates Resolve duplicate groups

	Resolve duplicate groups by synchronizing metadata across assets and deleting/trashing duplicates.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiResolveDuplicatesRequest
	*/
	ResolveDuplicates(ctx context.Context) ApiResolveDuplicatesRequest

	// ResolveDuplicatesExecute executes the request
	//  @return []BulkIdResponseDto
	ResolveDuplicatesExecute(r ApiResolveDuplicatesRequest) ([]BulkIdResponseDto, *http.Response, error)
}

// DuplicatesAPIService DuplicatesAPI service
type DuplicatesAPIService service

type ApiDeleteDuplicateRequest struct {
	ctx context.Context
	ApiService DuplicatesAPI
	id string
}

func (r ApiDeleteDuplicateRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteDuplicateExecute(r)
}

/*
DeleteDuplicate Dismiss a duplicate group

Dismiss a duplicate group by its ID, unlinking all assets in the group without deleting them.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return ApiDeleteDuplicateRequest
*/
func (a *DuplicatesAPIService) DeleteDuplicate(ctx context.Context, id string) ApiDeleteDuplicateRequest {
	return ApiDeleteDuplicateRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *DuplicatesAPIService) DeleteDuplicateExecute(r ApiDeleteDuplicateRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DuplicatesAPIService.DeleteDuplicate")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/duplicates/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["api_key"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-api-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiDeleteDuplicatesRequest struct {
	ctx context.Context
	ApiService DuplicatesAPI
	bulkIdsDto *BulkIdsDto
}

func (r ApiDeleteDuplicatesRequest) BulkIdsDto(bulkIdsDto BulkIdsDto) ApiDeleteDuplicatesRequest {
	r.bulkIdsDto = &bulkIdsDto
	return r
}

func (r ApiDeleteDuplicatesRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteDuplicatesExecute(r)
}

/*
DeleteDuplicates Delete duplicates

Delete multiple duplicate assets specified by their IDs.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiDeleteDuplicatesRequest
*/
func (a *DuplicatesAPIService) DeleteDuplicates(ctx context.Context) ApiDeleteDuplicatesRequest {
	return ApiDeleteDuplicatesRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *DuplicatesAPIService) DeleteDuplicatesExecute(r ApiDeleteDuplicatesRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DuplicatesAPIService.DeleteDuplicates")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/duplicates"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.bulkIdsDto == nil {
		return nil, reportError("bulkIdsDto is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.bulkIdsDto
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["api_key"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-api-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetAssetDuplicatesRequest struct {
	ctx context.Context
	ApiService DuplicatesAPI
}

func (r ApiGetAssetDuplicatesRequest) Execute() ([]DuplicateResponseDto, *http.Response, error) {
	return r.ApiService.GetAssetDuplicatesExecute(r)
}

/*
GetAssetDuplicates Retrieve duplicates

Retrieve a list of duplicate assets available to the authenticated user.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetAssetDuplicatesRequest
*/
func (a *DuplicatesAPIService) GetAssetDuplicates(ctx context.Context) ApiGetAssetDuplicatesRequest {
	return ApiGetAssetDuplicatesRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []DuplicateResponseDto
func (a *DuplicatesAPIService) GetAssetDuplicatesExecute(r ApiGetAssetDuplicatesRequest) ([]DuplicateResponseDto, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []DuplicateResponseDto
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DuplicatesAPIService.GetAssetDuplicates")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/duplicates"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["api_key"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-api-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiResolveDuplicatesRequest struct {
	ctx context.Context
	ApiService DuplicatesAPI
	duplicateResolveDto *DuplicateResolveDto
}

func (r ApiResolveDuplicatesRequest) DuplicateResolveDto(duplicateResolveDto DuplicateResolveDto) ApiResolveDuplicatesRequest {
	r.duplicateResolveDto = &duplicateResolveDto
	return r
}

func (r ApiResolveDuplicatesRequest) Execute() ([]BulkIdResponseDto, *http.Response, error) {
	return r.ApiService.ResolveDuplicatesExecute(r)
}

/*
ResolveDuplicates Resolve duplicate groups

Resolve duplicate groups by synchronizing metadata across assets and deleting/trashing duplicates.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiResolveDuplicatesRequest
*/
func (a *DuplicatesAPIService) ResolveDuplicates(ctx context.Context) ApiResolveDuplicatesRequest {
	return ApiResolveDuplicatesRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []BulkIdResponseDto
func (a *DuplicatesAPIService) ResolveDuplicatesExecute(r ApiResolveDuplicatesRequest) ([]BulkIdResponseDto, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []BulkIdResponseDto
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DuplicatesAPIService.ResolveDuplicates")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/duplicates/resolve"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.duplicateResolveDto == nil {
		return localVarReturnValue, nil, reportError("duplicateResolveDto is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.duplicateResolveDto
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["api_key"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-api-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
