/*
Immich

Immich API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the ChangePasswordDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangePasswordDto{}

// ChangePasswordDto struct for ChangePasswordDto
type ChangePasswordDto struct {
	// Invalidate all other sessions
	InvalidateSessions *bool `json:"invalidateSessions,omitempty"`
	// New password (min 8 characters)
	NewPassword string `json:"newPassword"`
	// Current password
	Password string `json:"password"`
	AdditionalProperties map[string]interface{}
}

type _ChangePasswordDto ChangePasswordDto

// NewChangePasswordDto instantiates a new ChangePasswordDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangePasswordDto(newPassword string, password string) *ChangePasswordDto {
	this := ChangePasswordDto{}
	var invalidateSessions bool = false
	this.InvalidateSessions = &invalidateSessions
	this.NewPassword = newPassword
	this.Password = password
	return &this
}

// NewChangePasswordDtoWithDefaults instantiates a new ChangePasswordDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangePasswordDtoWithDefaults() *ChangePasswordDto {
	this := ChangePasswordDto{}
	var invalidateSessions bool = false
	this.InvalidateSessions = &invalidateSessions
	return &this
}

// GetInvalidateSessions returns the InvalidateSessions field value if set, zero value otherwise.
func (o *ChangePasswordDto) GetInvalidateSessions() bool {
	if o == nil || IsNil(o.InvalidateSessions) {
		var ret bool
		return ret
	}
	return *o.InvalidateSessions
}

// GetInvalidateSessionsOk returns a tuple with the InvalidateSessions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangePasswordDto) GetInvalidateSessionsOk() (*bool, bool) {
	if o == nil || IsNil(o.InvalidateSessions) {
		return nil, false
	}
	return o.InvalidateSessions, true
}

// HasInvalidateSessions returns a boolean if a field has been set.
func (o *ChangePasswordDto) HasInvalidateSessions() bool {
	if o != nil && !IsNil(o.InvalidateSessions) {
		return true
	}

	return false
}

// SetInvalidateSessions gets a reference to the given bool and assigns it to the InvalidateSessions field.
func (o *ChangePasswordDto) SetInvalidateSessions(v bool) {
	o.InvalidateSessions = &v
}

// GetNewPassword returns the NewPassword field value
func (o *ChangePasswordDto) GetNewPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NewPassword
}

// GetNewPasswordOk returns a tuple with the NewPassword field value
// and a boolean to check if the value has been set.
func (o *ChangePasswordDto) GetNewPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewPassword, true
}

// SetNewPassword sets field value
func (o *ChangePasswordDto) SetNewPassword(v string) {
	o.NewPassword = v
}

// GetPassword returns the Password field value
func (o *ChangePasswordDto) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *ChangePasswordDto) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *ChangePasswordDto) SetPassword(v string) {
	o.Password = v
}

func (o ChangePasswordDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangePasswordDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InvalidateSessions) {
		toSerialize["invalidateSessions"] = o.InvalidateSessions
	}
	toSerialize["newPassword"] = o.NewPassword
	toSerialize["password"] = o.Password

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChangePasswordDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"newPassword",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChangePasswordDto := _ChangePasswordDto{}

	err = json.Unmarshal(data, &varChangePasswordDto)

	if err != nil {
		return err
	}

	*o = ChangePasswordDto(varChangePasswordDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "invalidateSessions")
		delete(additionalProperties, "newPassword")
		delete(additionalProperties, "password")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChangePasswordDto struct {
	value *ChangePasswordDto
	isSet bool
}

func (v NullableChangePasswordDto) Get() *ChangePasswordDto {
	return v.value
}

func (v *NullableChangePasswordDto) Set(val *ChangePasswordDto) {
	v.value = val
	v.isSet = true
}

func (v NullableChangePasswordDto) IsSet() bool {
	return v.isSet
}

func (v *NullableChangePasswordDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangePasswordDto(val *ChangePasswordDto) *NullableChangePasswordDto {
	return &NullableChangePasswordDto{value: val, isSet: true}
}

func (v NullableChangePasswordDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangePasswordDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


