/*
Immich

Immich API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the MaintenanceStatusResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MaintenanceStatusResponseDto{}

// MaintenanceStatusResponseDto struct for MaintenanceStatusResponseDto
type MaintenanceStatusResponseDto struct {
	Action MaintenanceAction `json:"action"`
	Active bool `json:"active"`
	Error *string `json:"error,omitempty"`
	Progress *int32 `json:"progress,omitempty"`
	Task *string `json:"task,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MaintenanceStatusResponseDto MaintenanceStatusResponseDto

// NewMaintenanceStatusResponseDto instantiates a new MaintenanceStatusResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMaintenanceStatusResponseDto(action MaintenanceAction, active bool) *MaintenanceStatusResponseDto {
	this := MaintenanceStatusResponseDto{}
	this.Action = action
	this.Active = active
	return &this
}

// NewMaintenanceStatusResponseDtoWithDefaults instantiates a new MaintenanceStatusResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMaintenanceStatusResponseDtoWithDefaults() *MaintenanceStatusResponseDto {
	this := MaintenanceStatusResponseDto{}
	return &this
}

// GetAction returns the Action field value
func (o *MaintenanceStatusResponseDto) GetAction() MaintenanceAction {
	if o == nil {
		var ret MaintenanceAction
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *MaintenanceStatusResponseDto) GetActionOk() (*MaintenanceAction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *MaintenanceStatusResponseDto) SetAction(v MaintenanceAction) {
	o.Action = v
}

// GetActive returns the Active field value
func (o *MaintenanceStatusResponseDto) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *MaintenanceStatusResponseDto) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *MaintenanceStatusResponseDto) SetActive(v bool) {
	o.Active = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *MaintenanceStatusResponseDto) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceStatusResponseDto) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *MaintenanceStatusResponseDto) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *MaintenanceStatusResponseDto) SetError(v string) {
	o.Error = &v
}

// GetProgress returns the Progress field value if set, zero value otherwise.
func (o *MaintenanceStatusResponseDto) GetProgress() int32 {
	if o == nil || IsNil(o.Progress) {
		var ret int32
		return ret
	}
	return *o.Progress
}

// GetProgressOk returns a tuple with the Progress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceStatusResponseDto) GetProgressOk() (*int32, bool) {
	if o == nil || IsNil(o.Progress) {
		return nil, false
	}
	return o.Progress, true
}

// HasProgress returns a boolean if a field has been set.
func (o *MaintenanceStatusResponseDto) HasProgress() bool {
	if o != nil && !IsNil(o.Progress) {
		return true
	}

	return false
}

// SetProgress gets a reference to the given int32 and assigns it to the Progress field.
func (o *MaintenanceStatusResponseDto) SetProgress(v int32) {
	o.Progress = &v
}

// GetTask returns the Task field value if set, zero value otherwise.
func (o *MaintenanceStatusResponseDto) GetTask() string {
	if o == nil || IsNil(o.Task) {
		var ret string
		return ret
	}
	return *o.Task
}

// GetTaskOk returns a tuple with the Task field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceStatusResponseDto) GetTaskOk() (*string, bool) {
	if o == nil || IsNil(o.Task) {
		return nil, false
	}
	return o.Task, true
}

// HasTask returns a boolean if a field has been set.
func (o *MaintenanceStatusResponseDto) HasTask() bool {
	if o != nil && !IsNil(o.Task) {
		return true
	}

	return false
}

// SetTask gets a reference to the given string and assigns it to the Task field.
func (o *MaintenanceStatusResponseDto) SetTask(v string) {
	o.Task = &v
}

func (o MaintenanceStatusResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MaintenanceStatusResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	toSerialize["active"] = o.Active
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Progress) {
		toSerialize["progress"] = o.Progress
	}
	if !IsNil(o.Task) {
		toSerialize["task"] = o.Task
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MaintenanceStatusResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"active",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMaintenanceStatusResponseDto := _MaintenanceStatusResponseDto{}

	err = json.Unmarshal(data, &varMaintenanceStatusResponseDto)

	if err != nil {
		return err
	}

	*o = MaintenanceStatusResponseDto(varMaintenanceStatusResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "action")
		delete(additionalProperties, "active")
		delete(additionalProperties, "error")
		delete(additionalProperties, "progress")
		delete(additionalProperties, "task")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMaintenanceStatusResponseDto struct {
	value *MaintenanceStatusResponseDto
	isSet bool
}

func (v NullableMaintenanceStatusResponseDto) Get() *MaintenanceStatusResponseDto {
	return v.value
}

func (v *NullableMaintenanceStatusResponseDto) Set(val *MaintenanceStatusResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableMaintenanceStatusResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableMaintenanceStatusResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMaintenanceStatusResponseDto(val *MaintenanceStatusResponseDto) *NullableMaintenanceStatusResponseDto {
	return &NullableMaintenanceStatusResponseDto{value: val, isSet: true}
}

func (v NullableMaintenanceStatusResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMaintenanceStatusResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


