/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the SearchAlbumResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchAlbumResponseDto{}

// SearchAlbumResponseDto struct for SearchAlbumResponseDto
type SearchAlbumResponseDto struct {
	// Number of albums in this page
	Count int32 `json:"count"`
	Facets []SearchFacetResponseDto `json:"facets"`
	Items []AlbumResponseDto `json:"items"`
	// Total number of matching albums
	Total int32 `json:"total"`
	AdditionalProperties map[string]interface{}
}

type _SearchAlbumResponseDto SearchAlbumResponseDto

// NewSearchAlbumResponseDto instantiates a new SearchAlbumResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchAlbumResponseDto(count int32, facets []SearchFacetResponseDto, items []AlbumResponseDto, total int32) *SearchAlbumResponseDto {
	this := SearchAlbumResponseDto{}
	this.Count = count
	this.Facets = facets
	this.Items = items
	this.Total = total
	return &this
}

// NewSearchAlbumResponseDtoWithDefaults instantiates a new SearchAlbumResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchAlbumResponseDtoWithDefaults() *SearchAlbumResponseDto {
	this := SearchAlbumResponseDto{}
	return &this
}

// GetCount returns the Count field value
func (o *SearchAlbumResponseDto) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *SearchAlbumResponseDto) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *SearchAlbumResponseDto) SetCount(v int32) {
	o.Count = v
}

// GetFacets returns the Facets field value
func (o *SearchAlbumResponseDto) GetFacets() []SearchFacetResponseDto {
	if o == nil {
		var ret []SearchFacetResponseDto
		return ret
	}

	return o.Facets
}

// GetFacetsOk returns a tuple with the Facets field value
// and a boolean to check if the value has been set.
func (o *SearchAlbumResponseDto) GetFacetsOk() ([]SearchFacetResponseDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Facets, true
}

// SetFacets sets field value
func (o *SearchAlbumResponseDto) SetFacets(v []SearchFacetResponseDto) {
	o.Facets = v
}

// GetItems returns the Items field value
func (o *SearchAlbumResponseDto) GetItems() []AlbumResponseDto {
	if o == nil {
		var ret []AlbumResponseDto
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *SearchAlbumResponseDto) GetItemsOk() ([]AlbumResponseDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *SearchAlbumResponseDto) SetItems(v []AlbumResponseDto) {
	o.Items = v
}

// GetTotal returns the Total field value
func (o *SearchAlbumResponseDto) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *SearchAlbumResponseDto) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *SearchAlbumResponseDto) SetTotal(v int32) {
	o.Total = v
}

func (o SearchAlbumResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchAlbumResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["facets"] = o.Facets
	toSerialize["items"] = o.Items
	toSerialize["total"] = o.Total

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchAlbumResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"facets",
		"items",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchAlbumResponseDto := _SearchAlbumResponseDto{}

	err = json.Unmarshal(data, &varSearchAlbumResponseDto)

	if err != nil {
		return err
	}

	*o = SearchAlbumResponseDto(varSearchAlbumResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "count")
		delete(additionalProperties, "facets")
		delete(additionalProperties, "items")
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSearchAlbumResponseDto struct {
	value *SearchAlbumResponseDto
	isSet bool
}

func (v NullableSearchAlbumResponseDto) Get() *SearchAlbumResponseDto {
	return v.value
}

func (v *NullableSearchAlbumResponseDto) Set(val *SearchAlbumResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchAlbumResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchAlbumResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchAlbumResponseDto(val *SearchAlbumResponseDto) *NullableSearchAlbumResponseDto {
	return &NullableSearchAlbumResponseDto{value: val, isSet: true}
}

func (v NullableSearchAlbumResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchAlbumResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


