/*
Immich

Immich API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the SharedLinkCreateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SharedLinkCreateDto{}

// SharedLinkCreateDto struct for SharedLinkCreateDto
type SharedLinkCreateDto struct {
	// Album ID (for album sharing)
	AlbumId *string `json:"albumId,omitempty" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$"`
	// Allow downloads
	AllowDownload *bool `json:"allowDownload,omitempty"`
	// Allow uploads
	AllowUpload *bool `json:"allowUpload,omitempty"`
	// Asset IDs (for individual assets)
	AssetIds []string `json:"assetIds,omitempty"`
	// Link description
	Description NullableString `json:"description,omitempty"`
	// Expiration date
	ExpiresAt NullableTime `json:"expiresAt,omitempty" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
	// Link password
	Password NullableString `json:"password,omitempty"`
	// Show metadata
	ShowMetadata *bool `json:"showMetadata,omitempty"`
	// Custom URL slug
	Slug NullableString `json:"slug,omitempty"`
	Type SharedLinkType `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _SharedLinkCreateDto SharedLinkCreateDto

// NewSharedLinkCreateDto instantiates a new SharedLinkCreateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSharedLinkCreateDto(type_ SharedLinkType) *SharedLinkCreateDto {
	this := SharedLinkCreateDto{}
	var allowDownload bool = true
	this.AllowDownload = &allowDownload
	var showMetadata bool = true
	this.ShowMetadata = &showMetadata
	this.Type = type_
	return &this
}

// NewSharedLinkCreateDtoWithDefaults instantiates a new SharedLinkCreateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSharedLinkCreateDtoWithDefaults() *SharedLinkCreateDto {
	this := SharedLinkCreateDto{}
	var allowDownload bool = true
	this.AllowDownload = &allowDownload
	var showMetadata bool = true
	this.ShowMetadata = &showMetadata
	return &this
}

// GetAlbumId returns the AlbumId field value if set, zero value otherwise.
func (o *SharedLinkCreateDto) GetAlbumId() string {
	if o == nil || IsNil(o.AlbumId) {
		var ret string
		return ret
	}
	return *o.AlbumId
}

// GetAlbumIdOk returns a tuple with the AlbumId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharedLinkCreateDto) GetAlbumIdOk() (*string, bool) {
	if o == nil || IsNil(o.AlbumId) {
		return nil, false
	}
	return o.AlbumId, true
}

// HasAlbumId returns a boolean if a field has been set.
func (o *SharedLinkCreateDto) HasAlbumId() bool {
	if o != nil && !IsNil(o.AlbumId) {
		return true
	}

	return false
}

// SetAlbumId gets a reference to the given string and assigns it to the AlbumId field.
func (o *SharedLinkCreateDto) SetAlbumId(v string) {
	o.AlbumId = &v
}

// GetAllowDownload returns the AllowDownload field value if set, zero value otherwise.
func (o *SharedLinkCreateDto) GetAllowDownload() bool {
	if o == nil || IsNil(o.AllowDownload) {
		var ret bool
		return ret
	}
	return *o.AllowDownload
}

// GetAllowDownloadOk returns a tuple with the AllowDownload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharedLinkCreateDto) GetAllowDownloadOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowDownload) {
		return nil, false
	}
	return o.AllowDownload, true
}

// HasAllowDownload returns a boolean if a field has been set.
func (o *SharedLinkCreateDto) HasAllowDownload() bool {
	if o != nil && !IsNil(o.AllowDownload) {
		return true
	}

	return false
}

// SetAllowDownload gets a reference to the given bool and assigns it to the AllowDownload field.
func (o *SharedLinkCreateDto) SetAllowDownload(v bool) {
	o.AllowDownload = &v
}

// GetAllowUpload returns the AllowUpload field value if set, zero value otherwise.
func (o *SharedLinkCreateDto) GetAllowUpload() bool {
	if o == nil || IsNil(o.AllowUpload) {
		var ret bool
		return ret
	}
	return *o.AllowUpload
}

// GetAllowUploadOk returns a tuple with the AllowUpload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharedLinkCreateDto) GetAllowUploadOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowUpload) {
		return nil, false
	}
	return o.AllowUpload, true
}

// HasAllowUpload returns a boolean if a field has been set.
func (o *SharedLinkCreateDto) HasAllowUpload() bool {
	if o != nil && !IsNil(o.AllowUpload) {
		return true
	}

	return false
}

// SetAllowUpload gets a reference to the given bool and assigns it to the AllowUpload field.
func (o *SharedLinkCreateDto) SetAllowUpload(v bool) {
	o.AllowUpload = &v
}

// GetAssetIds returns the AssetIds field value if set, zero value otherwise.
func (o *SharedLinkCreateDto) GetAssetIds() []string {
	if o == nil || IsNil(o.AssetIds) {
		var ret []string
		return ret
	}
	return o.AssetIds
}

// GetAssetIdsOk returns a tuple with the AssetIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharedLinkCreateDto) GetAssetIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AssetIds) {
		return nil, false
	}
	return o.AssetIds, true
}

// HasAssetIds returns a boolean if a field has been set.
func (o *SharedLinkCreateDto) HasAssetIds() bool {
	if o != nil && !IsNil(o.AssetIds) {
		return true
	}

	return false
}

// SetAssetIds gets a reference to the given []string and assigns it to the AssetIds field.
func (o *SharedLinkCreateDto) SetAssetIds(v []string) {
	o.AssetIds = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SharedLinkCreateDto) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SharedLinkCreateDto) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *SharedLinkCreateDto) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *SharedLinkCreateDto) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *SharedLinkCreateDto) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *SharedLinkCreateDto) UnsetDescription() {
	o.Description.Unset()
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SharedLinkCreateDto) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SharedLinkCreateDto) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *SharedLinkCreateDto) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableTime and assigns it to the ExpiresAt field.
func (o *SharedLinkCreateDto) SetExpiresAt(v time.Time) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *SharedLinkCreateDto) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *SharedLinkCreateDto) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

// GetPassword returns the Password field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SharedLinkCreateDto) GetPassword() string {
	if o == nil || IsNil(o.Password.Get()) {
		var ret string
		return ret
	}
	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SharedLinkCreateDto) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// HasPassword returns a boolean if a field has been set.
func (o *SharedLinkCreateDto) HasPassword() bool {
	if o != nil && o.Password.IsSet() {
		return true
	}

	return false
}

// SetPassword gets a reference to the given NullableString and assigns it to the Password field.
func (o *SharedLinkCreateDto) SetPassword(v string) {
	o.Password.Set(&v)
}
// SetPasswordNil sets the value for Password to be an explicit nil
func (o *SharedLinkCreateDto) SetPasswordNil() {
	o.Password.Set(nil)
}

// UnsetPassword ensures that no value is present for Password, not even an explicit nil
func (o *SharedLinkCreateDto) UnsetPassword() {
	o.Password.Unset()
}

// GetShowMetadata returns the ShowMetadata field value if set, zero value otherwise.
func (o *SharedLinkCreateDto) GetShowMetadata() bool {
	if o == nil || IsNil(o.ShowMetadata) {
		var ret bool
		return ret
	}
	return *o.ShowMetadata
}

// GetShowMetadataOk returns a tuple with the ShowMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharedLinkCreateDto) GetShowMetadataOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowMetadata) {
		return nil, false
	}
	return o.ShowMetadata, true
}

// HasShowMetadata returns a boolean if a field has been set.
func (o *SharedLinkCreateDto) HasShowMetadata() bool {
	if o != nil && !IsNil(o.ShowMetadata) {
		return true
	}

	return false
}

// SetShowMetadata gets a reference to the given bool and assigns it to the ShowMetadata field.
func (o *SharedLinkCreateDto) SetShowMetadata(v bool) {
	o.ShowMetadata = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SharedLinkCreateDto) GetSlug() string {
	if o == nil || IsNil(o.Slug.Get()) {
		var ret string
		return ret
	}
	return *o.Slug.Get()
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SharedLinkCreateDto) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Slug.Get(), o.Slug.IsSet()
}

// HasSlug returns a boolean if a field has been set.
func (o *SharedLinkCreateDto) HasSlug() bool {
	if o != nil && o.Slug.IsSet() {
		return true
	}

	return false
}

// SetSlug gets a reference to the given NullableString and assigns it to the Slug field.
func (o *SharedLinkCreateDto) SetSlug(v string) {
	o.Slug.Set(&v)
}
// SetSlugNil sets the value for Slug to be an explicit nil
func (o *SharedLinkCreateDto) SetSlugNil() {
	o.Slug.Set(nil)
}

// UnsetSlug ensures that no value is present for Slug, not even an explicit nil
func (o *SharedLinkCreateDto) UnsetSlug() {
	o.Slug.Unset()
}

// GetType returns the Type field value
func (o *SharedLinkCreateDto) GetType() SharedLinkType {
	if o == nil {
		var ret SharedLinkType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SharedLinkCreateDto) GetTypeOk() (*SharedLinkType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SharedLinkCreateDto) SetType(v SharedLinkType) {
	o.Type = v
}

func (o SharedLinkCreateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SharedLinkCreateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AlbumId) {
		toSerialize["albumId"] = o.AlbumId
	}
	if !IsNil(o.AllowDownload) {
		toSerialize["allowDownload"] = o.AllowDownload
	}
	if !IsNil(o.AllowUpload) {
		toSerialize["allowUpload"] = o.AllowUpload
	}
	if !IsNil(o.AssetIds) {
		toSerialize["assetIds"] = o.AssetIds
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expiresAt"] = o.ExpiresAt.Get()
	}
	if o.Password.IsSet() {
		toSerialize["password"] = o.Password.Get()
	}
	if !IsNil(o.ShowMetadata) {
		toSerialize["showMetadata"] = o.ShowMetadata
	}
	if o.Slug.IsSet() {
		toSerialize["slug"] = o.Slug.Get()
	}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SharedLinkCreateDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSharedLinkCreateDto := _SharedLinkCreateDto{}

	err = json.Unmarshal(data, &varSharedLinkCreateDto)

	if err != nil {
		return err
	}

	*o = SharedLinkCreateDto(varSharedLinkCreateDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "albumId")
		delete(additionalProperties, "allowDownload")
		delete(additionalProperties, "allowUpload")
		delete(additionalProperties, "assetIds")
		delete(additionalProperties, "description")
		delete(additionalProperties, "expiresAt")
		delete(additionalProperties, "password")
		delete(additionalProperties, "showMetadata")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSharedLinkCreateDto struct {
	value *SharedLinkCreateDto
	isSet bool
}

func (v NullableSharedLinkCreateDto) Get() *SharedLinkCreateDto {
	return v.value
}

func (v *NullableSharedLinkCreateDto) Set(val *SharedLinkCreateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSharedLinkCreateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSharedLinkCreateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSharedLinkCreateDto(val *SharedLinkCreateDto) *NullableSharedLinkCreateDto {
	return &NullableSharedLinkCreateDto{value: val, isSet: true}
}

func (v NullableSharedLinkCreateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSharedLinkCreateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


