/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the FaceDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FaceDto{}

// FaceDto struct for FaceDto
type FaceDto struct {
	// Face ID
	Id string `json:"id" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$"`
	AdditionalProperties map[string]interface{}
}

type _FaceDto FaceDto

// NewFaceDto instantiates a new FaceDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFaceDto(id string) *FaceDto {
	this := FaceDto{}
	this.Id = id
	return &this
}

// NewFaceDtoWithDefaults instantiates a new FaceDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFaceDtoWithDefaults() *FaceDto {
	this := FaceDto{}
	return &this
}

// GetId returns the Id field value
func (o *FaceDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FaceDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FaceDto) SetId(v string) {
	o.Id = v
}

func (o FaceDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FaceDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FaceDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFaceDto := _FaceDto{}

	err = json.Unmarshal(data, &varFaceDto)

	if err != nil {
		return err
	}

	*o = FaceDto(varFaceDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFaceDto struct {
	value *FaceDto
	isSet bool
}

func (v NullableFaceDto) Get() *FaceDto {
	return v.value
}

func (v *NullableFaceDto) Set(val *FaceDto) {
	v.value = val
	v.isSet = true
}

func (v NullableFaceDto) IsSet() bool {
	return v.isSet
}

func (v *NullableFaceDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFaceDto(val *FaceDto) *NullableFaceDto {
	return &NullableFaceDto{value: val, isSet: true}
}

func (v NullableFaceDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFaceDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


