/*
Immich

Immich API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the SyncUserV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncUserV1{}

// SyncUserV1 struct for SyncUserV1
type SyncUserV1 struct {
	AvatarColor NullableUserAvatarColor `json:"avatarColor,omitempty"`
	// User deleted at
	DeletedAt NullableTime `json:"deletedAt" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
	// User email
	Email string `json:"email"`
	// User has profile image
	HasProfileImage bool `json:"hasProfileImage"`
	// User ID
	Id string `json:"id"`
	// User name
	Name string `json:"name"`
	// User profile changed at
	ProfileChangedAt time.Time `json:"profileChangedAt" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
	AdditionalProperties map[string]interface{}
}

type _SyncUserV1 SyncUserV1

// NewSyncUserV1 instantiates a new SyncUserV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncUserV1(deletedAt NullableTime, email string, hasProfileImage bool, id string, name string, profileChangedAt time.Time) *SyncUserV1 {
	this := SyncUserV1{}
	this.DeletedAt = deletedAt
	this.Email = email
	this.HasProfileImage = hasProfileImage
	this.Id = id
	this.Name = name
	this.ProfileChangedAt = profileChangedAt
	return &this
}

// NewSyncUserV1WithDefaults instantiates a new SyncUserV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncUserV1WithDefaults() *SyncUserV1 {
	this := SyncUserV1{}
	return &this
}

// GetAvatarColor returns the AvatarColor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SyncUserV1) GetAvatarColor() UserAvatarColor {
	if o == nil || IsNil(o.AvatarColor.Get()) {
		var ret UserAvatarColor
		return ret
	}
	return *o.AvatarColor.Get()
}

// GetAvatarColorOk returns a tuple with the AvatarColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SyncUserV1) GetAvatarColorOk() (*UserAvatarColor, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvatarColor.Get(), o.AvatarColor.IsSet()
}

// HasAvatarColor returns a boolean if a field has been set.
func (o *SyncUserV1) HasAvatarColor() bool {
	if o != nil && o.AvatarColor.IsSet() {
		return true
	}

	return false
}

// SetAvatarColor gets a reference to the given NullableUserAvatarColor and assigns it to the AvatarColor field.
func (o *SyncUserV1) SetAvatarColor(v UserAvatarColor) {
	o.AvatarColor.Set(&v)
}
// SetAvatarColorNil sets the value for AvatarColor to be an explicit nil
func (o *SyncUserV1) SetAvatarColorNil() {
	o.AvatarColor.Set(nil)
}

// UnsetAvatarColor ensures that no value is present for AvatarColor, not even an explicit nil
func (o *SyncUserV1) UnsetAvatarColor() {
	o.AvatarColor.Unset()
}

// GetDeletedAt returns the DeletedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *SyncUserV1) GetDeletedAt() time.Time {
	if o == nil || o.DeletedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.DeletedAt.Get()
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SyncUserV1) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeletedAt.Get(), o.DeletedAt.IsSet()
}

// SetDeletedAt sets field value
func (o *SyncUserV1) SetDeletedAt(v time.Time) {
	o.DeletedAt.Set(&v)
}

// GetEmail returns the Email field value
func (o *SyncUserV1) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *SyncUserV1) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *SyncUserV1) SetEmail(v string) {
	o.Email = v
}

// GetHasProfileImage returns the HasProfileImage field value
func (o *SyncUserV1) GetHasProfileImage() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasProfileImage
}

// GetHasProfileImageOk returns a tuple with the HasProfileImage field value
// and a boolean to check if the value has been set.
func (o *SyncUserV1) GetHasProfileImageOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasProfileImage, true
}

// SetHasProfileImage sets field value
func (o *SyncUserV1) SetHasProfileImage(v bool) {
	o.HasProfileImage = v
}

// GetId returns the Id field value
func (o *SyncUserV1) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SyncUserV1) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SyncUserV1) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *SyncUserV1) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SyncUserV1) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SyncUserV1) SetName(v string) {
	o.Name = v
}

// GetProfileChangedAt returns the ProfileChangedAt field value
func (o *SyncUserV1) GetProfileChangedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ProfileChangedAt
}

// GetProfileChangedAtOk returns a tuple with the ProfileChangedAt field value
// and a boolean to check if the value has been set.
func (o *SyncUserV1) GetProfileChangedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProfileChangedAt, true
}

// SetProfileChangedAt sets field value
func (o *SyncUserV1) SetProfileChangedAt(v time.Time) {
	o.ProfileChangedAt = v
}

func (o SyncUserV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncUserV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AvatarColor.IsSet() {
		toSerialize["avatarColor"] = o.AvatarColor.Get()
	}
	toSerialize["deletedAt"] = o.DeletedAt.Get()
	toSerialize["email"] = o.Email
	toSerialize["hasProfileImage"] = o.HasProfileImage
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["profileChangedAt"] = o.ProfileChangedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SyncUserV1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deletedAt",
		"email",
		"hasProfileImage",
		"id",
		"name",
		"profileChangedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSyncUserV1 := _SyncUserV1{}

	err = json.Unmarshal(data, &varSyncUserV1)

	if err != nil {
		return err
	}

	*o = SyncUserV1(varSyncUserV1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "avatarColor")
		delete(additionalProperties, "deletedAt")
		delete(additionalProperties, "email")
		delete(additionalProperties, "hasProfileImage")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "profileChangedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSyncUserV1 struct {
	value *SyncUserV1
	isSet bool
}

func (v NullableSyncUserV1) Get() *SyncUserV1 {
	return v.value
}

func (v *NullableSyncUserV1) Set(val *SyncUserV1) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncUserV1) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncUserV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncUserV1(val *SyncUserV1) *NullableSyncUserV1 {
	return &NullableSyncUserV1{value: val, isSet: true}
}

func (v NullableSyncUserV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncUserV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


