/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"time"
)

// checks if the StatisticsSearchDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatisticsSearchDto{}

// StatisticsSearchDto struct for StatisticsSearchDto
type StatisticsSearchDto struct {
	// Filter by album IDs
	AlbumIds []string `json:"albumIds,omitempty"`
	// Filter by city name
	City NullableString `json:"city,omitempty"`
	// Filter by country name
	Country NullableString `json:"country,omitempty"`
	// Filter by creation date (after)
	CreatedAfter *time.Time `json:"createdAfter,omitempty" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
	// Filter by creation date (before)
	CreatedBefore *time.Time `json:"createdBefore,omitempty" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
	// Filter by description text
	Description *string `json:"description,omitempty"`
	// Filter by encoded status
	IsEncoded *bool `json:"isEncoded,omitempty"`
	// Filter by favorite status
	IsFavorite *bool `json:"isFavorite,omitempty"`
	// Filter by motion photo status
	IsMotion *bool `json:"isMotion,omitempty"`
	// Filter assets not in any album
	IsNotInAlbum *bool `json:"isNotInAlbum,omitempty"`
	// Filter by offline status
	IsOffline *bool `json:"isOffline,omitempty"`
	// Filter by lens model
	LensModel NullableString `json:"lensModel,omitempty"`
	// Library ID to filter by
	LibraryId NullableString `json:"libraryId,omitempty" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$"`
	// Filter by camera make
	Make NullableString `json:"make,omitempty"`
	// Filter by camera model
	Model NullableString `json:"model,omitempty"`
	// Filter by OCR text content
	Ocr *string `json:"ocr,omitempty"`
	// Filter by person IDs
	PersonIds []string `json:"personIds,omitempty"`
	// Filter by rating [1-5], or null for unrated
	Rating NullableFloat32 `json:"rating,omitempty"`
	// Filter by state/province name
	State NullableString `json:"state,omitempty"`
	// Filter by tag IDs
	TagIds []string `json:"tagIds,omitempty"`
	// Filter by taken date (after)
	TakenAfter *time.Time `json:"takenAfter,omitempty" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
	// Filter by taken date (before)
	TakenBefore *time.Time `json:"takenBefore,omitempty" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
	// Filter by trash date (after)
	TrashedAfter *time.Time `json:"trashedAfter,omitempty" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
	// Filter by trash date (before)
	TrashedBefore *time.Time `json:"trashedBefore,omitempty" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
	Type *AssetTypeEnum `json:"type,omitempty"`
	// Filter by update date (after)
	UpdatedAfter *time.Time `json:"updatedAfter,omitempty" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
	// Filter by update date (before)
	UpdatedBefore *time.Time `json:"updatedBefore,omitempty" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
	Visibility *AssetVisibility `json:"visibility,omitempty"`
}

// NewStatisticsSearchDto instantiates a new StatisticsSearchDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatisticsSearchDto() *StatisticsSearchDto {
	this := StatisticsSearchDto{}
	return &this
}

// NewStatisticsSearchDtoWithDefaults instantiates a new StatisticsSearchDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatisticsSearchDtoWithDefaults() *StatisticsSearchDto {
	this := StatisticsSearchDto{}
	return &this
}

// GetAlbumIds returns the AlbumIds field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetAlbumIds() []string {
	if o == nil || IsNil(o.AlbumIds) {
		var ret []string
		return ret
	}
	return o.AlbumIds
}

// GetAlbumIdsOk returns a tuple with the AlbumIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetAlbumIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AlbumIds) {
		return nil, false
	}
	return o.AlbumIds, true
}

// HasAlbumIds returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasAlbumIds() bool {
	if o != nil && !IsNil(o.AlbumIds) {
		return true
	}

	return false
}

// SetAlbumIds gets a reference to the given []string and assigns it to the AlbumIds field.
func (o *StatisticsSearchDto) SetAlbumIds(v []string) {
	o.AlbumIds = v
}

// GetCity returns the City field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StatisticsSearchDto) GetCity() string {
	if o == nil || IsNil(o.City.Get()) {
		var ret string
		return ret
	}
	return *o.City.Get()
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StatisticsSearchDto) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.City.Get(), o.City.IsSet()
}

// HasCity returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasCity() bool {
	if o != nil && o.City.IsSet() {
		return true
	}

	return false
}

// SetCity gets a reference to the given NullableString and assigns it to the City field.
func (o *StatisticsSearchDto) SetCity(v string) {
	o.City.Set(&v)
}
// SetCityNil sets the value for City to be an explicit nil
func (o *StatisticsSearchDto) SetCityNil() {
	o.City.Set(nil)
}

// UnsetCity ensures that no value is present for City, not even an explicit nil
func (o *StatisticsSearchDto) UnsetCity() {
	o.City.Unset()
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StatisticsSearchDto) GetCountry() string {
	if o == nil || IsNil(o.Country.Get()) {
		var ret string
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StatisticsSearchDto) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableString and assigns it to the Country field.
func (o *StatisticsSearchDto) SetCountry(v string) {
	o.Country.Set(&v)
}
// SetCountryNil sets the value for Country to be an explicit nil
func (o *StatisticsSearchDto) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *StatisticsSearchDto) UnsetCountry() {
	o.Country.Unset()
}

// GetCreatedAfter returns the CreatedAfter field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetCreatedAfter() time.Time {
	if o == nil || IsNil(o.CreatedAfter) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAfter
}

// GetCreatedAfterOk returns a tuple with the CreatedAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetCreatedAfterOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAfter) {
		return nil, false
	}
	return o.CreatedAfter, true
}

// HasCreatedAfter returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasCreatedAfter() bool {
	if o != nil && !IsNil(o.CreatedAfter) {
		return true
	}

	return false
}

// SetCreatedAfter gets a reference to the given time.Time and assigns it to the CreatedAfter field.
func (o *StatisticsSearchDto) SetCreatedAfter(v time.Time) {
	o.CreatedAfter = &v
}

// GetCreatedBefore returns the CreatedBefore field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetCreatedBefore() time.Time {
	if o == nil || IsNil(o.CreatedBefore) {
		var ret time.Time
		return ret
	}
	return *o.CreatedBefore
}

// GetCreatedBeforeOk returns a tuple with the CreatedBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetCreatedBeforeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedBefore) {
		return nil, false
	}
	return o.CreatedBefore, true
}

// HasCreatedBefore returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasCreatedBefore() bool {
	if o != nil && !IsNil(o.CreatedBefore) {
		return true
	}

	return false
}

// SetCreatedBefore gets a reference to the given time.Time and assigns it to the CreatedBefore field.
func (o *StatisticsSearchDto) SetCreatedBefore(v time.Time) {
	o.CreatedBefore = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *StatisticsSearchDto) SetDescription(v string) {
	o.Description = &v
}

// GetIsEncoded returns the IsEncoded field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetIsEncoded() bool {
	if o == nil || IsNil(o.IsEncoded) {
		var ret bool
		return ret
	}
	return *o.IsEncoded
}

// GetIsEncodedOk returns a tuple with the IsEncoded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetIsEncodedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEncoded) {
		return nil, false
	}
	return o.IsEncoded, true
}

// HasIsEncoded returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasIsEncoded() bool {
	if o != nil && !IsNil(o.IsEncoded) {
		return true
	}

	return false
}

// SetIsEncoded gets a reference to the given bool and assigns it to the IsEncoded field.
func (o *StatisticsSearchDto) SetIsEncoded(v bool) {
	o.IsEncoded = &v
}

// GetIsFavorite returns the IsFavorite field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetIsFavorite() bool {
	if o == nil || IsNil(o.IsFavorite) {
		var ret bool
		return ret
	}
	return *o.IsFavorite
}

// GetIsFavoriteOk returns a tuple with the IsFavorite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetIsFavoriteOk() (*bool, bool) {
	if o == nil || IsNil(o.IsFavorite) {
		return nil, false
	}
	return o.IsFavorite, true
}

// HasIsFavorite returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasIsFavorite() bool {
	if o != nil && !IsNil(o.IsFavorite) {
		return true
	}

	return false
}

// SetIsFavorite gets a reference to the given bool and assigns it to the IsFavorite field.
func (o *StatisticsSearchDto) SetIsFavorite(v bool) {
	o.IsFavorite = &v
}

// GetIsMotion returns the IsMotion field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetIsMotion() bool {
	if o == nil || IsNil(o.IsMotion) {
		var ret bool
		return ret
	}
	return *o.IsMotion
}

// GetIsMotionOk returns a tuple with the IsMotion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetIsMotionOk() (*bool, bool) {
	if o == nil || IsNil(o.IsMotion) {
		return nil, false
	}
	return o.IsMotion, true
}

// HasIsMotion returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasIsMotion() bool {
	if o != nil && !IsNil(o.IsMotion) {
		return true
	}

	return false
}

// SetIsMotion gets a reference to the given bool and assigns it to the IsMotion field.
func (o *StatisticsSearchDto) SetIsMotion(v bool) {
	o.IsMotion = &v
}

// GetIsNotInAlbum returns the IsNotInAlbum field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetIsNotInAlbum() bool {
	if o == nil || IsNil(o.IsNotInAlbum) {
		var ret bool
		return ret
	}
	return *o.IsNotInAlbum
}

// GetIsNotInAlbumOk returns a tuple with the IsNotInAlbum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetIsNotInAlbumOk() (*bool, bool) {
	if o == nil || IsNil(o.IsNotInAlbum) {
		return nil, false
	}
	return o.IsNotInAlbum, true
}

// HasIsNotInAlbum returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasIsNotInAlbum() bool {
	if o != nil && !IsNil(o.IsNotInAlbum) {
		return true
	}

	return false
}

// SetIsNotInAlbum gets a reference to the given bool and assigns it to the IsNotInAlbum field.
func (o *StatisticsSearchDto) SetIsNotInAlbum(v bool) {
	o.IsNotInAlbum = &v
}

// GetIsOffline returns the IsOffline field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetIsOffline() bool {
	if o == nil || IsNil(o.IsOffline) {
		var ret bool
		return ret
	}
	return *o.IsOffline
}

// GetIsOfflineOk returns a tuple with the IsOffline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetIsOfflineOk() (*bool, bool) {
	if o == nil || IsNil(o.IsOffline) {
		return nil, false
	}
	return o.IsOffline, true
}

// HasIsOffline returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasIsOffline() bool {
	if o != nil && !IsNil(o.IsOffline) {
		return true
	}

	return false
}

// SetIsOffline gets a reference to the given bool and assigns it to the IsOffline field.
func (o *StatisticsSearchDto) SetIsOffline(v bool) {
	o.IsOffline = &v
}

// GetLensModel returns the LensModel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StatisticsSearchDto) GetLensModel() string {
	if o == nil || IsNil(o.LensModel.Get()) {
		var ret string
		return ret
	}
	return *o.LensModel.Get()
}

// GetLensModelOk returns a tuple with the LensModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StatisticsSearchDto) GetLensModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LensModel.Get(), o.LensModel.IsSet()
}

// HasLensModel returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasLensModel() bool {
	if o != nil && o.LensModel.IsSet() {
		return true
	}

	return false
}

// SetLensModel gets a reference to the given NullableString and assigns it to the LensModel field.
func (o *StatisticsSearchDto) SetLensModel(v string) {
	o.LensModel.Set(&v)
}
// SetLensModelNil sets the value for LensModel to be an explicit nil
func (o *StatisticsSearchDto) SetLensModelNil() {
	o.LensModel.Set(nil)
}

// UnsetLensModel ensures that no value is present for LensModel, not even an explicit nil
func (o *StatisticsSearchDto) UnsetLensModel() {
	o.LensModel.Unset()
}

// GetLibraryId returns the LibraryId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StatisticsSearchDto) GetLibraryId() string {
	if o == nil || IsNil(o.LibraryId.Get()) {
		var ret string
		return ret
	}
	return *o.LibraryId.Get()
}

// GetLibraryIdOk returns a tuple with the LibraryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StatisticsSearchDto) GetLibraryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LibraryId.Get(), o.LibraryId.IsSet()
}

// HasLibraryId returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasLibraryId() bool {
	if o != nil && o.LibraryId.IsSet() {
		return true
	}

	return false
}

// SetLibraryId gets a reference to the given NullableString and assigns it to the LibraryId field.
func (o *StatisticsSearchDto) SetLibraryId(v string) {
	o.LibraryId.Set(&v)
}
// SetLibraryIdNil sets the value for LibraryId to be an explicit nil
func (o *StatisticsSearchDto) SetLibraryIdNil() {
	o.LibraryId.Set(nil)
}

// UnsetLibraryId ensures that no value is present for LibraryId, not even an explicit nil
func (o *StatisticsSearchDto) UnsetLibraryId() {
	o.LibraryId.Unset()
}

// GetMake returns the Make field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StatisticsSearchDto) GetMake() string {
	if o == nil || IsNil(o.Make.Get()) {
		var ret string
		return ret
	}
	return *o.Make.Get()
}

// GetMakeOk returns a tuple with the Make field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StatisticsSearchDto) GetMakeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Make.Get(), o.Make.IsSet()
}

// HasMake returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasMake() bool {
	if o != nil && o.Make.IsSet() {
		return true
	}

	return false
}

// SetMake gets a reference to the given NullableString and assigns it to the Make field.
func (o *StatisticsSearchDto) SetMake(v string) {
	o.Make.Set(&v)
}
// SetMakeNil sets the value for Make to be an explicit nil
func (o *StatisticsSearchDto) SetMakeNil() {
	o.Make.Set(nil)
}

// UnsetMake ensures that no value is present for Make, not even an explicit nil
func (o *StatisticsSearchDto) UnsetMake() {
	o.Make.Unset()
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StatisticsSearchDto) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StatisticsSearchDto) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *StatisticsSearchDto) SetModel(v string) {
	o.Model.Set(&v)
}
// SetModelNil sets the value for Model to be an explicit nil
func (o *StatisticsSearchDto) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *StatisticsSearchDto) UnsetModel() {
	o.Model.Unset()
}

// GetOcr returns the Ocr field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetOcr() string {
	if o == nil || IsNil(o.Ocr) {
		var ret string
		return ret
	}
	return *o.Ocr
}

// GetOcrOk returns a tuple with the Ocr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetOcrOk() (*string, bool) {
	if o == nil || IsNil(o.Ocr) {
		return nil, false
	}
	return o.Ocr, true
}

// HasOcr returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasOcr() bool {
	if o != nil && !IsNil(o.Ocr) {
		return true
	}

	return false
}

// SetOcr gets a reference to the given string and assigns it to the Ocr field.
func (o *StatisticsSearchDto) SetOcr(v string) {
	o.Ocr = &v
}

// GetPersonIds returns the PersonIds field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetPersonIds() []string {
	if o == nil || IsNil(o.PersonIds) {
		var ret []string
		return ret
	}
	return o.PersonIds
}

// GetPersonIdsOk returns a tuple with the PersonIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetPersonIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.PersonIds) {
		return nil, false
	}
	return o.PersonIds, true
}

// HasPersonIds returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasPersonIds() bool {
	if o != nil && !IsNil(o.PersonIds) {
		return true
	}

	return false
}

// SetPersonIds gets a reference to the given []string and assigns it to the PersonIds field.
func (o *StatisticsSearchDto) SetPersonIds(v []string) {
	o.PersonIds = v
}

// GetRating returns the Rating field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StatisticsSearchDto) GetRating() float32 {
	if o == nil || IsNil(o.Rating.Get()) {
		var ret float32
		return ret
	}
	return *o.Rating.Get()
}

// GetRatingOk returns a tuple with the Rating field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StatisticsSearchDto) GetRatingOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rating.Get(), o.Rating.IsSet()
}

// HasRating returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasRating() bool {
	if o != nil && o.Rating.IsSet() {
		return true
	}

	return false
}

// SetRating gets a reference to the given NullableFloat32 and assigns it to the Rating field.
func (o *StatisticsSearchDto) SetRating(v float32) {
	o.Rating.Set(&v)
}
// SetRatingNil sets the value for Rating to be an explicit nil
func (o *StatisticsSearchDto) SetRatingNil() {
	o.Rating.Set(nil)
}

// UnsetRating ensures that no value is present for Rating, not even an explicit nil
func (o *StatisticsSearchDto) UnsetRating() {
	o.Rating.Unset()
}

// GetState returns the State field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StatisticsSearchDto) GetState() string {
	if o == nil || IsNil(o.State.Get()) {
		var ret string
		return ret
	}
	return *o.State.Get()
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StatisticsSearchDto) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.State.Get(), o.State.IsSet()
}

// HasState returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasState() bool {
	if o != nil && o.State.IsSet() {
		return true
	}

	return false
}

// SetState gets a reference to the given NullableString and assigns it to the State field.
func (o *StatisticsSearchDto) SetState(v string) {
	o.State.Set(&v)
}
// SetStateNil sets the value for State to be an explicit nil
func (o *StatisticsSearchDto) SetStateNil() {
	o.State.Set(nil)
}

// UnsetState ensures that no value is present for State, not even an explicit nil
func (o *StatisticsSearchDto) UnsetState() {
	o.State.Unset()
}

// GetTagIds returns the TagIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StatisticsSearchDto) GetTagIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.TagIds
}

// GetTagIdsOk returns a tuple with the TagIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StatisticsSearchDto) GetTagIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.TagIds) {
		return nil, false
	}
	return o.TagIds, true
}

// HasTagIds returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasTagIds() bool {
	if o != nil && !IsNil(o.TagIds) {
		return true
	}

	return false
}

// SetTagIds gets a reference to the given []string and assigns it to the TagIds field.
func (o *StatisticsSearchDto) SetTagIds(v []string) {
	o.TagIds = v
}

// GetTakenAfter returns the TakenAfter field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetTakenAfter() time.Time {
	if o == nil || IsNil(o.TakenAfter) {
		var ret time.Time
		return ret
	}
	return *o.TakenAfter
}

// GetTakenAfterOk returns a tuple with the TakenAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetTakenAfterOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TakenAfter) {
		return nil, false
	}
	return o.TakenAfter, true
}

// HasTakenAfter returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasTakenAfter() bool {
	if o != nil && !IsNil(o.TakenAfter) {
		return true
	}

	return false
}

// SetTakenAfter gets a reference to the given time.Time and assigns it to the TakenAfter field.
func (o *StatisticsSearchDto) SetTakenAfter(v time.Time) {
	o.TakenAfter = &v
}

// GetTakenBefore returns the TakenBefore field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetTakenBefore() time.Time {
	if o == nil || IsNil(o.TakenBefore) {
		var ret time.Time
		return ret
	}
	return *o.TakenBefore
}

// GetTakenBeforeOk returns a tuple with the TakenBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetTakenBeforeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TakenBefore) {
		return nil, false
	}
	return o.TakenBefore, true
}

// HasTakenBefore returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasTakenBefore() bool {
	if o != nil && !IsNil(o.TakenBefore) {
		return true
	}

	return false
}

// SetTakenBefore gets a reference to the given time.Time and assigns it to the TakenBefore field.
func (o *StatisticsSearchDto) SetTakenBefore(v time.Time) {
	o.TakenBefore = &v
}

// GetTrashedAfter returns the TrashedAfter field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetTrashedAfter() time.Time {
	if o == nil || IsNil(o.TrashedAfter) {
		var ret time.Time
		return ret
	}
	return *o.TrashedAfter
}

// GetTrashedAfterOk returns a tuple with the TrashedAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetTrashedAfterOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TrashedAfter) {
		return nil, false
	}
	return o.TrashedAfter, true
}

// HasTrashedAfter returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasTrashedAfter() bool {
	if o != nil && !IsNil(o.TrashedAfter) {
		return true
	}

	return false
}

// SetTrashedAfter gets a reference to the given time.Time and assigns it to the TrashedAfter field.
func (o *StatisticsSearchDto) SetTrashedAfter(v time.Time) {
	o.TrashedAfter = &v
}

// GetTrashedBefore returns the TrashedBefore field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetTrashedBefore() time.Time {
	if o == nil || IsNil(o.TrashedBefore) {
		var ret time.Time
		return ret
	}
	return *o.TrashedBefore
}

// GetTrashedBeforeOk returns a tuple with the TrashedBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetTrashedBeforeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TrashedBefore) {
		return nil, false
	}
	return o.TrashedBefore, true
}

// HasTrashedBefore returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasTrashedBefore() bool {
	if o != nil && !IsNil(o.TrashedBefore) {
		return true
	}

	return false
}

// SetTrashedBefore gets a reference to the given time.Time and assigns it to the TrashedBefore field.
func (o *StatisticsSearchDto) SetTrashedBefore(v time.Time) {
	o.TrashedBefore = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetType() AssetTypeEnum {
	if o == nil || IsNil(o.Type) {
		var ret AssetTypeEnum
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetTypeOk() (*AssetTypeEnum, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given AssetTypeEnum and assigns it to the Type field.
func (o *StatisticsSearchDto) SetType(v AssetTypeEnum) {
	o.Type = &v
}

// GetUpdatedAfter returns the UpdatedAfter field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetUpdatedAfter() time.Time {
	if o == nil || IsNil(o.UpdatedAfter) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAfter
}

// GetUpdatedAfterOk returns a tuple with the UpdatedAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetUpdatedAfterOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAfter) {
		return nil, false
	}
	return o.UpdatedAfter, true
}

// HasUpdatedAfter returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasUpdatedAfter() bool {
	if o != nil && !IsNil(o.UpdatedAfter) {
		return true
	}

	return false
}

// SetUpdatedAfter gets a reference to the given time.Time and assigns it to the UpdatedAfter field.
func (o *StatisticsSearchDto) SetUpdatedAfter(v time.Time) {
	o.UpdatedAfter = &v
}

// GetUpdatedBefore returns the UpdatedBefore field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetUpdatedBefore() time.Time {
	if o == nil || IsNil(o.UpdatedBefore) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedBefore
}

// GetUpdatedBeforeOk returns a tuple with the UpdatedBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetUpdatedBeforeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedBefore) {
		return nil, false
	}
	return o.UpdatedBefore, true
}

// HasUpdatedBefore returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasUpdatedBefore() bool {
	if o != nil && !IsNil(o.UpdatedBefore) {
		return true
	}

	return false
}

// SetUpdatedBefore gets a reference to the given time.Time and assigns it to the UpdatedBefore field.
func (o *StatisticsSearchDto) SetUpdatedBefore(v time.Time) {
	o.UpdatedBefore = &v
}

// GetVisibility returns the Visibility field value if set, zero value otherwise.
func (o *StatisticsSearchDto) GetVisibility() AssetVisibility {
	if o == nil || IsNil(o.Visibility) {
		var ret AssetVisibility
		return ret
	}
	return *o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsSearchDto) GetVisibilityOk() (*AssetVisibility, bool) {
	if o == nil || IsNil(o.Visibility) {
		return nil, false
	}
	return o.Visibility, true
}

// HasVisibility returns a boolean if a field has been set.
func (o *StatisticsSearchDto) HasVisibility() bool {
	if o != nil && !IsNil(o.Visibility) {
		return true
	}

	return false
}

// SetVisibility gets a reference to the given AssetVisibility and assigns it to the Visibility field.
func (o *StatisticsSearchDto) SetVisibility(v AssetVisibility) {
	o.Visibility = &v
}

func (o StatisticsSearchDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatisticsSearchDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AlbumIds) {
		toSerialize["albumIds"] = o.AlbumIds
	}
	if o.City.IsSet() {
		toSerialize["city"] = o.City.Get()
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	if !IsNil(o.CreatedAfter) {
		toSerialize["createdAfter"] = o.CreatedAfter
	}
	if !IsNil(o.CreatedBefore) {
		toSerialize["createdBefore"] = o.CreatedBefore
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.IsEncoded) {
		toSerialize["isEncoded"] = o.IsEncoded
	}
	if !IsNil(o.IsFavorite) {
		toSerialize["isFavorite"] = o.IsFavorite
	}
	if !IsNil(o.IsMotion) {
		toSerialize["isMotion"] = o.IsMotion
	}
	if !IsNil(o.IsNotInAlbum) {
		toSerialize["isNotInAlbum"] = o.IsNotInAlbum
	}
	if !IsNil(o.IsOffline) {
		toSerialize["isOffline"] = o.IsOffline
	}
	if o.LensModel.IsSet() {
		toSerialize["lensModel"] = o.LensModel.Get()
	}
	if o.LibraryId.IsSet() {
		toSerialize["libraryId"] = o.LibraryId.Get()
	}
	if o.Make.IsSet() {
		toSerialize["make"] = o.Make.Get()
	}
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	if !IsNil(o.Ocr) {
		toSerialize["ocr"] = o.Ocr
	}
	if !IsNil(o.PersonIds) {
		toSerialize["personIds"] = o.PersonIds
	}
	if o.Rating.IsSet() {
		toSerialize["rating"] = o.Rating.Get()
	}
	if o.State.IsSet() {
		toSerialize["state"] = o.State.Get()
	}
	if o.TagIds != nil {
		toSerialize["tagIds"] = o.TagIds
	}
	if !IsNil(o.TakenAfter) {
		toSerialize["takenAfter"] = o.TakenAfter
	}
	if !IsNil(o.TakenBefore) {
		toSerialize["takenBefore"] = o.TakenBefore
	}
	if !IsNil(o.TrashedAfter) {
		toSerialize["trashedAfter"] = o.TrashedAfter
	}
	if !IsNil(o.TrashedBefore) {
		toSerialize["trashedBefore"] = o.TrashedBefore
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.UpdatedAfter) {
		toSerialize["updatedAfter"] = o.UpdatedAfter
	}
	if !IsNil(o.UpdatedBefore) {
		toSerialize["updatedBefore"] = o.UpdatedBefore
	}
	if !IsNil(o.Visibility) {
		toSerialize["visibility"] = o.Visibility
	}
	return toSerialize, nil
}

type NullableStatisticsSearchDto struct {
	value *StatisticsSearchDto
	isSet bool
}

func (v NullableStatisticsSearchDto) Get() *StatisticsSearchDto {
	return v.value
}

func (v *NullableStatisticsSearchDto) Set(val *StatisticsSearchDto) {
	v.value = val
	v.isSet = true
}

func (v NullableStatisticsSearchDto) IsSet() bool {
	return v.isSet
}

func (v *NullableStatisticsSearchDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatisticsSearchDto(val *StatisticsSearchDto) *NullableStatisticsSearchDto {
	return &NullableStatisticsSearchDto{value: val, isSet: true}
}

func (v NullableStatisticsSearchDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatisticsSearchDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


