/*
Immich

Immich API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
)

// checks if the PersonCreateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PersonCreateDto{}

// PersonCreateDto struct for PersonCreateDto
type PersonCreateDto struct {
	// Person date of birth
	BirthDate NullableString `json:"birthDate,omitempty"`
	// Person color (hex)
	Color NullableString `json:"color,omitempty" validate:"regexp=^#?([0-9A-Fa-f]{3}|[0-9A-Fa-f]{4}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$"`
	// Mark as favorite
	IsFavorite *bool `json:"isFavorite,omitempty"`
	// Person visibility (hidden)
	IsHidden *bool `json:"isHidden,omitempty"`
	// Person name
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PersonCreateDto PersonCreateDto

// NewPersonCreateDto instantiates a new PersonCreateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPersonCreateDto() *PersonCreateDto {
	this := PersonCreateDto{}
	return &this
}

// NewPersonCreateDtoWithDefaults instantiates a new PersonCreateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPersonCreateDtoWithDefaults() *PersonCreateDto {
	this := PersonCreateDto{}
	return &this
}

// GetBirthDate returns the BirthDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonCreateDto) GetBirthDate() string {
	if o == nil || IsNil(o.BirthDate.Get()) {
		var ret string
		return ret
	}
	return *o.BirthDate.Get()
}

// GetBirthDateOk returns a tuple with the BirthDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonCreateDto) GetBirthDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BirthDate.Get(), o.BirthDate.IsSet()
}

// HasBirthDate returns a boolean if a field has been set.
func (o *PersonCreateDto) HasBirthDate() bool {
	if o != nil && o.BirthDate.IsSet() {
		return true
	}

	return false
}

// SetBirthDate gets a reference to the given NullableString and assigns it to the BirthDate field.
func (o *PersonCreateDto) SetBirthDate(v string) {
	o.BirthDate.Set(&v)
}
// SetBirthDateNil sets the value for BirthDate to be an explicit nil
func (o *PersonCreateDto) SetBirthDateNil() {
	o.BirthDate.Set(nil)
}

// UnsetBirthDate ensures that no value is present for BirthDate, not even an explicit nil
func (o *PersonCreateDto) UnsetBirthDate() {
	o.BirthDate.Unset()
}

// GetColor returns the Color field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonCreateDto) GetColor() string {
	if o == nil || IsNil(o.Color.Get()) {
		var ret string
		return ret
	}
	return *o.Color.Get()
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonCreateDto) GetColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Color.Get(), o.Color.IsSet()
}

// HasColor returns a boolean if a field has been set.
func (o *PersonCreateDto) HasColor() bool {
	if o != nil && o.Color.IsSet() {
		return true
	}

	return false
}

// SetColor gets a reference to the given NullableString and assigns it to the Color field.
func (o *PersonCreateDto) SetColor(v string) {
	o.Color.Set(&v)
}
// SetColorNil sets the value for Color to be an explicit nil
func (o *PersonCreateDto) SetColorNil() {
	o.Color.Set(nil)
}

// UnsetColor ensures that no value is present for Color, not even an explicit nil
func (o *PersonCreateDto) UnsetColor() {
	o.Color.Unset()
}

// GetIsFavorite returns the IsFavorite field value if set, zero value otherwise.
func (o *PersonCreateDto) GetIsFavorite() bool {
	if o == nil || IsNil(o.IsFavorite) {
		var ret bool
		return ret
	}
	return *o.IsFavorite
}

// GetIsFavoriteOk returns a tuple with the IsFavorite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonCreateDto) GetIsFavoriteOk() (*bool, bool) {
	if o == nil || IsNil(o.IsFavorite) {
		return nil, false
	}
	return o.IsFavorite, true
}

// HasIsFavorite returns a boolean if a field has been set.
func (o *PersonCreateDto) HasIsFavorite() bool {
	if o != nil && !IsNil(o.IsFavorite) {
		return true
	}

	return false
}

// SetIsFavorite gets a reference to the given bool and assigns it to the IsFavorite field.
func (o *PersonCreateDto) SetIsFavorite(v bool) {
	o.IsFavorite = &v
}

// GetIsHidden returns the IsHidden field value if set, zero value otherwise.
func (o *PersonCreateDto) GetIsHidden() bool {
	if o == nil || IsNil(o.IsHidden) {
		var ret bool
		return ret
	}
	return *o.IsHidden
}

// GetIsHiddenOk returns a tuple with the IsHidden field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonCreateDto) GetIsHiddenOk() (*bool, bool) {
	if o == nil || IsNil(o.IsHidden) {
		return nil, false
	}
	return o.IsHidden, true
}

// HasIsHidden returns a boolean if a field has been set.
func (o *PersonCreateDto) HasIsHidden() bool {
	if o != nil && !IsNil(o.IsHidden) {
		return true
	}

	return false
}

// SetIsHidden gets a reference to the given bool and assigns it to the IsHidden field.
func (o *PersonCreateDto) SetIsHidden(v bool) {
	o.IsHidden = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PersonCreateDto) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonCreateDto) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PersonCreateDto) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PersonCreateDto) SetName(v string) {
	o.Name = &v
}

func (o PersonCreateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PersonCreateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.BirthDate.IsSet() {
		toSerialize["birthDate"] = o.BirthDate.Get()
	}
	if o.Color.IsSet() {
		toSerialize["color"] = o.Color.Get()
	}
	if !IsNil(o.IsFavorite) {
		toSerialize["isFavorite"] = o.IsFavorite
	}
	if !IsNil(o.IsHidden) {
		toSerialize["isHidden"] = o.IsHidden
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PersonCreateDto) UnmarshalJSON(data []byte) (err error) {
	varPersonCreateDto := _PersonCreateDto{}

	err = json.Unmarshal(data, &varPersonCreateDto)

	if err != nil {
		return err
	}

	*o = PersonCreateDto(varPersonCreateDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "birthDate")
		delete(additionalProperties, "color")
		delete(additionalProperties, "isFavorite")
		delete(additionalProperties, "isHidden")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePersonCreateDto struct {
	value *PersonCreateDto
	isSet bool
}

func (v NullablePersonCreateDto) Get() *PersonCreateDto {
	return v.value
}

func (v *NullablePersonCreateDto) Set(val *PersonCreateDto) {
	v.value = val
	v.isSet = true
}

func (v NullablePersonCreateDto) IsSet() bool {
	return v.isSet
}

func (v *NullablePersonCreateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePersonCreateDto(val *PersonCreateDto) *NullablePersonCreateDto {
	return &NullablePersonCreateDto{value: val, isSet: true}
}

func (v NullablePersonCreateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePersonCreateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


