/*
Immich

Immich API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// MemoryType Memory type
type MemoryType string

// List of MemoryType
const (
	MEMORYTYPE_ON_THIS_DAY MemoryType = "on_this_day"
)

// All allowed values of MemoryType enum
var AllowedMemoryTypeEnumValues = []MemoryType{
	"on_this_day",
}

func (v *MemoryType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := MemoryType(value)
	for _, existing := range AllowedMemoryTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid MemoryType", value)
}

// NewMemoryTypeFromValue returns a pointer to a valid MemoryType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewMemoryTypeFromValue(v string) (*MemoryType, error) {
	ev := MemoryType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for MemoryType: valid values are %v", v, AllowedMemoryTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v MemoryType) IsValid() bool {
	for _, existing := range AllowedMemoryTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to MemoryType value
func (v MemoryType) Ptr() *MemoryType {
	return &v
}

type NullableMemoryType struct {
	value *MemoryType
	isSet bool
}

func (v NullableMemoryType) Get() *MemoryType {
	return v.value
}

func (v *NullableMemoryType) Set(val *MemoryType) {
	v.value = val
	v.isSet = true
}

func (v NullableMemoryType) IsSet() bool {
	return v.isSet
}

func (v *NullableMemoryType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemoryType(val *MemoryType) *NullableMemoryType {
	return &NullableMemoryType{value: val, isSet: true}
}

func (v NullableMemoryType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemoryType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

