/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// SyncEntityType Sync entity type
type SyncEntityType string

// List of SyncEntityType
const (
	SYNCENTITYTYPE_AUTH_USER_V1 SyncEntityType = "AuthUserV1"
	SYNCENTITYTYPE_USER_V1 SyncEntityType = "UserV1"
	SYNCENTITYTYPE_USER_DELETE_V1 SyncEntityType = "UserDeleteV1"
	SYNCENTITYTYPE_ASSET_V1 SyncEntityType = "AssetV1"
	SYNCENTITYTYPE_ASSET_DELETE_V1 SyncEntityType = "AssetDeleteV1"
	SYNCENTITYTYPE_ASSET_EXIF_V1 SyncEntityType = "AssetExifV1"
	SYNCENTITYTYPE_ASSET_EDIT_V1 SyncEntityType = "AssetEditV1"
	SYNCENTITYTYPE_ASSET_EDIT_DELETE_V1 SyncEntityType = "AssetEditDeleteV1"
	SYNCENTITYTYPE_ASSET_METADATA_V1 SyncEntityType = "AssetMetadataV1"
	SYNCENTITYTYPE_ASSET_METADATA_DELETE_V1 SyncEntityType = "AssetMetadataDeleteV1"
	SYNCENTITYTYPE_PARTNER_V1 SyncEntityType = "PartnerV1"
	SYNCENTITYTYPE_PARTNER_DELETE_V1 SyncEntityType = "PartnerDeleteV1"
	SYNCENTITYTYPE_PARTNER_ASSET_V1 SyncEntityType = "PartnerAssetV1"
	SYNCENTITYTYPE_PARTNER_ASSET_BACKFILL_V1 SyncEntityType = "PartnerAssetBackfillV1"
	SYNCENTITYTYPE_PARTNER_ASSET_DELETE_V1 SyncEntityType = "PartnerAssetDeleteV1"
	SYNCENTITYTYPE_PARTNER_ASSET_EXIF_V1 SyncEntityType = "PartnerAssetExifV1"
	SYNCENTITYTYPE_PARTNER_ASSET_EXIF_BACKFILL_V1 SyncEntityType = "PartnerAssetExifBackfillV1"
	SYNCENTITYTYPE_PARTNER_STACK_BACKFILL_V1 SyncEntityType = "PartnerStackBackfillV1"
	SYNCENTITYTYPE_PARTNER_STACK_DELETE_V1 SyncEntityType = "PartnerStackDeleteV1"
	SYNCENTITYTYPE_PARTNER_STACK_V1 SyncEntityType = "PartnerStackV1"
	SYNCENTITYTYPE_ALBUM_V1 SyncEntityType = "AlbumV1"
	SYNCENTITYTYPE_ALBUM_V2 SyncEntityType = "AlbumV2"
	SYNCENTITYTYPE_ALBUM_DELETE_V1 SyncEntityType = "AlbumDeleteV1"
	SYNCENTITYTYPE_ALBUM_USER_V1 SyncEntityType = "AlbumUserV1"
	SYNCENTITYTYPE_ALBUM_USER_BACKFILL_V1 SyncEntityType = "AlbumUserBackfillV1"
	SYNCENTITYTYPE_ALBUM_USER_DELETE_V1 SyncEntityType = "AlbumUserDeleteV1"
	SYNCENTITYTYPE_ALBUM_ASSET_CREATE_V1 SyncEntityType = "AlbumAssetCreateV1"
	SYNCENTITYTYPE_ALBUM_ASSET_UPDATE_V1 SyncEntityType = "AlbumAssetUpdateV1"
	SYNCENTITYTYPE_ALBUM_ASSET_BACKFILL_V1 SyncEntityType = "AlbumAssetBackfillV1"
	SYNCENTITYTYPE_ALBUM_ASSET_EXIF_CREATE_V1 SyncEntityType = "AlbumAssetExifCreateV1"
	SYNCENTITYTYPE_ALBUM_ASSET_EXIF_UPDATE_V1 SyncEntityType = "AlbumAssetExifUpdateV1"
	SYNCENTITYTYPE_ALBUM_ASSET_EXIF_BACKFILL_V1 SyncEntityType = "AlbumAssetExifBackfillV1"
	SYNCENTITYTYPE_ALBUM_TO_ASSET_V1 SyncEntityType = "AlbumToAssetV1"
	SYNCENTITYTYPE_ALBUM_TO_ASSET_DELETE_V1 SyncEntityType = "AlbumToAssetDeleteV1"
	SYNCENTITYTYPE_ALBUM_TO_ASSET_BACKFILL_V1 SyncEntityType = "AlbumToAssetBackfillV1"
	SYNCENTITYTYPE_MEMORY_V1 SyncEntityType = "MemoryV1"
	SYNCENTITYTYPE_MEMORY_DELETE_V1 SyncEntityType = "MemoryDeleteV1"
	SYNCENTITYTYPE_MEMORY_TO_ASSET_V1 SyncEntityType = "MemoryToAssetV1"
	SYNCENTITYTYPE_MEMORY_TO_ASSET_DELETE_V1 SyncEntityType = "MemoryToAssetDeleteV1"
	SYNCENTITYTYPE_STACK_V1 SyncEntityType = "StackV1"
	SYNCENTITYTYPE_STACK_DELETE_V1 SyncEntityType = "StackDeleteV1"
	SYNCENTITYTYPE_PERSON_V1 SyncEntityType = "PersonV1"
	SYNCENTITYTYPE_PERSON_DELETE_V1 SyncEntityType = "PersonDeleteV1"
	SYNCENTITYTYPE_ASSET_FACE_V1 SyncEntityType = "AssetFaceV1"
	SYNCENTITYTYPE_ASSET_FACE_V2 SyncEntityType = "AssetFaceV2"
	SYNCENTITYTYPE_ASSET_FACE_DELETE_V1 SyncEntityType = "AssetFaceDeleteV1"
	SYNCENTITYTYPE_USER_METADATA_V1 SyncEntityType = "UserMetadataV1"
	SYNCENTITYTYPE_USER_METADATA_DELETE_V1 SyncEntityType = "UserMetadataDeleteV1"
	SYNCENTITYTYPE_SYNC_ACK_V1 SyncEntityType = "SyncAckV1"
	SYNCENTITYTYPE_SYNC_RESET_V1 SyncEntityType = "SyncResetV1"
	SYNCENTITYTYPE_SYNC_COMPLETE_V1 SyncEntityType = "SyncCompleteV1"
)

// All allowed values of SyncEntityType enum
var AllowedSyncEntityTypeEnumValues = []SyncEntityType{
	"AuthUserV1",
	"UserV1",
	"UserDeleteV1",
	"AssetV1",
	"AssetDeleteV1",
	"AssetExifV1",
	"AssetEditV1",
	"AssetEditDeleteV1",
	"AssetMetadataV1",
	"AssetMetadataDeleteV1",
	"PartnerV1",
	"PartnerDeleteV1",
	"PartnerAssetV1",
	"PartnerAssetBackfillV1",
	"PartnerAssetDeleteV1",
	"PartnerAssetExifV1",
	"PartnerAssetExifBackfillV1",
	"PartnerStackBackfillV1",
	"PartnerStackDeleteV1",
	"PartnerStackV1",
	"AlbumV1",
	"AlbumV2",
	"AlbumDeleteV1",
	"AlbumUserV1",
	"AlbumUserBackfillV1",
	"AlbumUserDeleteV1",
	"AlbumAssetCreateV1",
	"AlbumAssetUpdateV1",
	"AlbumAssetBackfillV1",
	"AlbumAssetExifCreateV1",
	"AlbumAssetExifUpdateV1",
	"AlbumAssetExifBackfillV1",
	"AlbumToAssetV1",
	"AlbumToAssetDeleteV1",
	"AlbumToAssetBackfillV1",
	"MemoryV1",
	"MemoryDeleteV1",
	"MemoryToAssetV1",
	"MemoryToAssetDeleteV1",
	"StackV1",
	"StackDeleteV1",
	"PersonV1",
	"PersonDeleteV1",
	"AssetFaceV1",
	"AssetFaceV2",
	"AssetFaceDeleteV1",
	"UserMetadataV1",
	"UserMetadataDeleteV1",
	"SyncAckV1",
	"SyncResetV1",
	"SyncCompleteV1",
}

func (v *SyncEntityType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SyncEntityType(value)
	for _, existing := range AllowedSyncEntityTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SyncEntityType", value)
}

// NewSyncEntityTypeFromValue returns a pointer to a valid SyncEntityType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSyncEntityTypeFromValue(v string) (*SyncEntityType, error) {
	ev := SyncEntityType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SyncEntityType: valid values are %v", v, AllowedSyncEntityTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SyncEntityType) IsValid() bool {
	for _, existing := range AllowedSyncEntityTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SyncEntityType value
func (v SyncEntityType) Ptr() *SyncEntityType {
	return &v
}

type NullableSyncEntityType struct {
	value *SyncEntityType
	isSet bool
}

func (v NullableSyncEntityType) Get() *SyncEntityType {
	return v.value
}

func (v *NullableSyncEntityType) Set(val *SyncEntityType) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncEntityType) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncEntityType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncEntityType(val *SyncEntityType) *NullableSyncEntityType {
	return &NullableSyncEntityType{value: val, isSet: true}
}

func (v NullableSyncEntityType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncEntityType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

