/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the SystemConfigTrashDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemConfigTrashDto{}

// SystemConfigTrashDto struct for SystemConfigTrashDto
type SystemConfigTrashDto struct {
	// Days
	Days int32 `json:"days"`
	// Enabled
	Enabled bool `json:"enabled"`
	AdditionalProperties map[string]interface{}
}

type _SystemConfigTrashDto SystemConfigTrashDto

// NewSystemConfigTrashDto instantiates a new SystemConfigTrashDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemConfigTrashDto(days int32, enabled bool) *SystemConfigTrashDto {
	this := SystemConfigTrashDto{}
	this.Days = days
	this.Enabled = enabled
	return &this
}

// NewSystemConfigTrashDtoWithDefaults instantiates a new SystemConfigTrashDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemConfigTrashDtoWithDefaults() *SystemConfigTrashDto {
	this := SystemConfigTrashDto{}
	return &this
}

// GetDays returns the Days field value
func (o *SystemConfigTrashDto) GetDays() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Days
}

// GetDaysOk returns a tuple with the Days field value
// and a boolean to check if the value has been set.
func (o *SystemConfigTrashDto) GetDaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Days, true
}

// SetDays sets field value
func (o *SystemConfigTrashDto) SetDays(v int32) {
	o.Days = v
}

// GetEnabled returns the Enabled field value
func (o *SystemConfigTrashDto) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *SystemConfigTrashDto) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *SystemConfigTrashDto) SetEnabled(v bool) {
	o.Enabled = v
}

func (o SystemConfigTrashDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemConfigTrashDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["days"] = o.Days
	toSerialize["enabled"] = o.Enabled

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SystemConfigTrashDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"days",
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemConfigTrashDto := _SystemConfigTrashDto{}

	err = json.Unmarshal(data, &varSystemConfigTrashDto)

	if err != nil {
		return err
	}

	*o = SystemConfigTrashDto(varSystemConfigTrashDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "days")
		delete(additionalProperties, "enabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSystemConfigTrashDto struct {
	value *SystemConfigTrashDto
	isSet bool
}

func (v NullableSystemConfigTrashDto) Get() *SystemConfigTrashDto {
	return v.value
}

func (v *NullableSystemConfigTrashDto) Set(val *SystemConfigTrashDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemConfigTrashDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemConfigTrashDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemConfigTrashDto(val *SystemConfigTrashDto) *NullableSystemConfigTrashDto {
	return &NullableSystemConfigTrashDto{value: val, isSet: true}
}

func (v NullableSystemConfigTrashDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemConfigTrashDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


