/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QueueJobResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueueJobResponseDto{}

// QueueJobResponseDto struct for QueueJobResponseDto
type QueueJobResponseDto struct {
	// Job data payload
	Data map[string]interface{} `json:"data"`
	// Job ID
	Id *string `json:"id,omitempty"`
	Name JobName `json:"name"`
	// Job creation timestamp
	Timestamp int32 `json:"timestamp"`
}

type _QueueJobResponseDto QueueJobResponseDto

// NewQueueJobResponseDto instantiates a new QueueJobResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueueJobResponseDto(data map[string]interface{}, name JobName, timestamp int32) *QueueJobResponseDto {
	this := QueueJobResponseDto{}
	this.Data = data
	this.Name = name
	this.Timestamp = timestamp
	return &this
}

// NewQueueJobResponseDtoWithDefaults instantiates a new QueueJobResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueueJobResponseDtoWithDefaults() *QueueJobResponseDto {
	this := QueueJobResponseDto{}
	return &this
}

// GetData returns the Data field value
func (o *QueueJobResponseDto) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *QueueJobResponseDto) GetDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *QueueJobResponseDto) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *QueueJobResponseDto) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueJobResponseDto) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *QueueJobResponseDto) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *QueueJobResponseDto) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *QueueJobResponseDto) GetName() JobName {
	if o == nil {
		var ret JobName
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *QueueJobResponseDto) GetNameOk() (*JobName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *QueueJobResponseDto) SetName(v JobName) {
	o.Name = v
}

// GetTimestamp returns the Timestamp field value
func (o *QueueJobResponseDto) GetTimestamp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *QueueJobResponseDto) GetTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *QueueJobResponseDto) SetTimestamp(v int32) {
	o.Timestamp = v
}

func (o QueueJobResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueueJobResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	toSerialize["timestamp"] = o.Timestamp
	return toSerialize, nil
}

func (o *QueueJobResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"name",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueueJobResponseDto := _QueueJobResponseDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueueJobResponseDto)

	if err != nil {
		return err
	}

	*o = QueueJobResponseDto(varQueueJobResponseDto)

	return err
}

type NullableQueueJobResponseDto struct {
	value *QueueJobResponseDto
	isSet bool
}

func (v NullableQueueJobResponseDto) Get() *QueueJobResponseDto {
	return v.value
}

func (v *NullableQueueJobResponseDto) Set(val *QueueJobResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableQueueJobResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableQueueJobResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueueJobResponseDto(val *QueueJobResponseDto) *NullableQueueJobResponseDto {
	return &NullableQueueJobResponseDto{value: val, isSet: true}
}

func (v NullableQueueJobResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueueJobResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


