/*
Immich

Immich API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// AssetEditAction Type of edit action to perform
type AssetEditAction string

// List of AssetEditAction
const (
	ASSETEDITACTION_CROP AssetEditAction = "crop"
	ASSETEDITACTION_ROTATE AssetEditAction = "rotate"
	ASSETEDITACTION_MIRROR AssetEditAction = "mirror"
)

// All allowed values of AssetEditAction enum
var AllowedAssetEditActionEnumValues = []AssetEditAction{
	"crop",
	"rotate",
	"mirror",
}

func (v *AssetEditAction) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AssetEditAction(value)
	for _, existing := range AllowedAssetEditActionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AssetEditAction", value)
}

// NewAssetEditActionFromValue returns a pointer to a valid AssetEditAction
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAssetEditActionFromValue(v string) (*AssetEditAction, error) {
	ev := AssetEditAction(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AssetEditAction: valid values are %v", v, AllowedAssetEditActionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AssetEditAction) IsValid() bool {
	for _, existing := range AllowedAssetEditActionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AssetEditAction value
func (v AssetEditAction) Ptr() *AssetEditAction {
	return &v
}

type NullableAssetEditAction struct {
	value *AssetEditAction
	isSet bool
}

func (v NullableAssetEditAction) Get() *AssetEditAction {
	return v.value
}

func (v *NullableAssetEditAction) Set(val *AssetEditAction) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetEditAction) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetEditAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetEditAction(val *AssetEditAction) *NullableAssetEditAction {
	return &NullableAssetEditAction{value: val, isSet: true}
}

func (v NullableAssetEditAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetEditAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

