/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the AssetFaceUpdateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetFaceUpdateDto{}

// AssetFaceUpdateDto struct for AssetFaceUpdateDto
type AssetFaceUpdateDto struct {
	// Face update items
	Data []AssetFaceUpdateItem `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _AssetFaceUpdateDto AssetFaceUpdateDto

// NewAssetFaceUpdateDto instantiates a new AssetFaceUpdateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetFaceUpdateDto(data []AssetFaceUpdateItem) *AssetFaceUpdateDto {
	this := AssetFaceUpdateDto{}
	this.Data = data
	return &this
}

// NewAssetFaceUpdateDtoWithDefaults instantiates a new AssetFaceUpdateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetFaceUpdateDtoWithDefaults() *AssetFaceUpdateDto {
	this := AssetFaceUpdateDto{}
	return &this
}

// GetData returns the Data field value
func (o *AssetFaceUpdateDto) GetData() []AssetFaceUpdateItem {
	if o == nil {
		var ret []AssetFaceUpdateItem
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AssetFaceUpdateDto) GetDataOk() ([]AssetFaceUpdateItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *AssetFaceUpdateDto) SetData(v []AssetFaceUpdateItem) {
	o.Data = v
}

func (o AssetFaceUpdateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetFaceUpdateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AssetFaceUpdateDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssetFaceUpdateDto := _AssetFaceUpdateDto{}

	err = json.Unmarshal(data, &varAssetFaceUpdateDto)

	if err != nil {
		return err
	}

	*o = AssetFaceUpdateDto(varAssetFaceUpdateDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAssetFaceUpdateDto struct {
	value *AssetFaceUpdateDto
	isSet bool
}

func (v NullableAssetFaceUpdateDto) Get() *AssetFaceUpdateDto {
	return v.value
}

func (v *NullableAssetFaceUpdateDto) Set(val *AssetFaceUpdateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetFaceUpdateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetFaceUpdateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetFaceUpdateDto(val *AssetFaceUpdateDto) *NullableAssetFaceUpdateDto {
	return &NullableAssetFaceUpdateDto{value: val, isSet: true}
}

func (v NullableAssetFaceUpdateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetFaceUpdateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


