/*
Immich

Immich API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the SystemConfigOAuthDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemConfigOAuthDto{}

// SystemConfigOAuthDto struct for SystemConfigOAuthDto
type SystemConfigOAuthDto struct {
	// Allow insecure requests
	AllowInsecureRequests bool `json:"allowInsecureRequests"`
	// Auto launch
	AutoLaunch bool `json:"autoLaunch"`
	// Auto register
	AutoRegister bool `json:"autoRegister"`
	// Button text
	ButtonText string `json:"buttonText"`
	// Client ID
	ClientId string `json:"clientId"`
	// Client secret
	ClientSecret string `json:"clientSecret"`
	// Default storage quota
	DefaultStorageQuota NullableInt32 `json:"defaultStorageQuota"`
	// Enabled
	Enabled bool `json:"enabled"`
	// End session endpoint
	EndSessionEndpoint string `json:"endSessionEndpoint"`
	// Issuer URL
	IssuerUrl string `json:"issuerUrl"`
	// Mobile override enabled
	MobileOverrideEnabled bool `json:"mobileOverrideEnabled"`
	// Mobile redirect URI (set to empty string to disable)
	MobileRedirectUri string `json:"mobileRedirectUri"`
	// Profile signing algorithm
	ProfileSigningAlgorithm string `json:"profileSigningAlgorithm"`
	// OAuth prompt parameter (e.g. select_account, login, consent)
	Prompt string `json:"prompt"`
	// Role claim
	RoleClaim string `json:"roleClaim"`
	// Scope
	Scope string `json:"scope"`
	// Signing algorithm
	SigningAlgorithm string `json:"signingAlgorithm"`
	// Storage label claim
	StorageLabelClaim string `json:"storageLabelClaim"`
	// Storage quota claim
	StorageQuotaClaim string `json:"storageQuotaClaim"`
	// Timeout
	Timeout int32 `json:"timeout"`
	TokenEndpointAuthMethod OAuthTokenEndpointAuthMethod `json:"tokenEndpointAuthMethod"`
	AdditionalProperties map[string]interface{}
}

type _SystemConfigOAuthDto SystemConfigOAuthDto

// NewSystemConfigOAuthDto instantiates a new SystemConfigOAuthDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemConfigOAuthDto(allowInsecureRequests bool, autoLaunch bool, autoRegister bool, buttonText string, clientId string, clientSecret string, defaultStorageQuota NullableInt32, enabled bool, endSessionEndpoint string, issuerUrl string, mobileOverrideEnabled bool, mobileRedirectUri string, profileSigningAlgorithm string, prompt string, roleClaim string, scope string, signingAlgorithm string, storageLabelClaim string, storageQuotaClaim string, timeout int32, tokenEndpointAuthMethod OAuthTokenEndpointAuthMethod) *SystemConfigOAuthDto {
	this := SystemConfigOAuthDto{}
	this.AllowInsecureRequests = allowInsecureRequests
	this.AutoLaunch = autoLaunch
	this.AutoRegister = autoRegister
	this.ButtonText = buttonText
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	this.DefaultStorageQuota = defaultStorageQuota
	this.Enabled = enabled
	this.EndSessionEndpoint = endSessionEndpoint
	this.IssuerUrl = issuerUrl
	this.MobileOverrideEnabled = mobileOverrideEnabled
	this.MobileRedirectUri = mobileRedirectUri
	this.ProfileSigningAlgorithm = profileSigningAlgorithm
	this.Prompt = prompt
	this.RoleClaim = roleClaim
	this.Scope = scope
	this.SigningAlgorithm = signingAlgorithm
	this.StorageLabelClaim = storageLabelClaim
	this.StorageQuotaClaim = storageQuotaClaim
	this.Timeout = timeout
	this.TokenEndpointAuthMethod = tokenEndpointAuthMethod
	return &this
}

// NewSystemConfigOAuthDtoWithDefaults instantiates a new SystemConfigOAuthDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemConfigOAuthDtoWithDefaults() *SystemConfigOAuthDto {
	this := SystemConfigOAuthDto{}
	return &this
}

// GetAllowInsecureRequests returns the AllowInsecureRequests field value
func (o *SystemConfigOAuthDto) GetAllowInsecureRequests() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AllowInsecureRequests
}

// GetAllowInsecureRequestsOk returns a tuple with the AllowInsecureRequests field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetAllowInsecureRequestsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AllowInsecureRequests, true
}

// SetAllowInsecureRequests sets field value
func (o *SystemConfigOAuthDto) SetAllowInsecureRequests(v bool) {
	o.AllowInsecureRequests = v
}

// GetAutoLaunch returns the AutoLaunch field value
func (o *SystemConfigOAuthDto) GetAutoLaunch() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AutoLaunch
}

// GetAutoLaunchOk returns a tuple with the AutoLaunch field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetAutoLaunchOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AutoLaunch, true
}

// SetAutoLaunch sets field value
func (o *SystemConfigOAuthDto) SetAutoLaunch(v bool) {
	o.AutoLaunch = v
}

// GetAutoRegister returns the AutoRegister field value
func (o *SystemConfigOAuthDto) GetAutoRegister() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AutoRegister
}

// GetAutoRegisterOk returns a tuple with the AutoRegister field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetAutoRegisterOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AutoRegister, true
}

// SetAutoRegister sets field value
func (o *SystemConfigOAuthDto) SetAutoRegister(v bool) {
	o.AutoRegister = v
}

// GetButtonText returns the ButtonText field value
func (o *SystemConfigOAuthDto) GetButtonText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ButtonText
}

// GetButtonTextOk returns a tuple with the ButtonText field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetButtonTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ButtonText, true
}

// SetButtonText sets field value
func (o *SystemConfigOAuthDto) SetButtonText(v string) {
	o.ButtonText = v
}

// GetClientId returns the ClientId field value
func (o *SystemConfigOAuthDto) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *SystemConfigOAuthDto) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *SystemConfigOAuthDto) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *SystemConfigOAuthDto) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetDefaultStorageQuota returns the DefaultStorageQuota field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *SystemConfigOAuthDto) GetDefaultStorageQuota() int32 {
	if o == nil || o.DefaultStorageQuota.Get() == nil {
		var ret int32
		return ret
	}

	return *o.DefaultStorageQuota.Get()
}

// GetDefaultStorageQuotaOk returns a tuple with the DefaultStorageQuota field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SystemConfigOAuthDto) GetDefaultStorageQuotaOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultStorageQuota.Get(), o.DefaultStorageQuota.IsSet()
}

// SetDefaultStorageQuota sets field value
func (o *SystemConfigOAuthDto) SetDefaultStorageQuota(v int32) {
	o.DefaultStorageQuota.Set(&v)
}

// GetEnabled returns the Enabled field value
func (o *SystemConfigOAuthDto) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *SystemConfigOAuthDto) SetEnabled(v bool) {
	o.Enabled = v
}

// GetEndSessionEndpoint returns the EndSessionEndpoint field value
func (o *SystemConfigOAuthDto) GetEndSessionEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndSessionEndpoint
}

// GetEndSessionEndpointOk returns a tuple with the EndSessionEndpoint field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetEndSessionEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndSessionEndpoint, true
}

// SetEndSessionEndpoint sets field value
func (o *SystemConfigOAuthDto) SetEndSessionEndpoint(v string) {
	o.EndSessionEndpoint = v
}

// GetIssuerUrl returns the IssuerUrl field value
func (o *SystemConfigOAuthDto) GetIssuerUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IssuerUrl
}

// GetIssuerUrlOk returns a tuple with the IssuerUrl field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetIssuerUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuerUrl, true
}

// SetIssuerUrl sets field value
func (o *SystemConfigOAuthDto) SetIssuerUrl(v string) {
	o.IssuerUrl = v
}

// GetMobileOverrideEnabled returns the MobileOverrideEnabled field value
func (o *SystemConfigOAuthDto) GetMobileOverrideEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.MobileOverrideEnabled
}

// GetMobileOverrideEnabledOk returns a tuple with the MobileOverrideEnabled field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetMobileOverrideEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MobileOverrideEnabled, true
}

// SetMobileOverrideEnabled sets field value
func (o *SystemConfigOAuthDto) SetMobileOverrideEnabled(v bool) {
	o.MobileOverrideEnabled = v
}

// GetMobileRedirectUri returns the MobileRedirectUri field value
func (o *SystemConfigOAuthDto) GetMobileRedirectUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MobileRedirectUri
}

// GetMobileRedirectUriOk returns a tuple with the MobileRedirectUri field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetMobileRedirectUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MobileRedirectUri, true
}

// SetMobileRedirectUri sets field value
func (o *SystemConfigOAuthDto) SetMobileRedirectUri(v string) {
	o.MobileRedirectUri = v
}

// GetProfileSigningAlgorithm returns the ProfileSigningAlgorithm field value
func (o *SystemConfigOAuthDto) GetProfileSigningAlgorithm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProfileSigningAlgorithm
}

// GetProfileSigningAlgorithmOk returns a tuple with the ProfileSigningAlgorithm field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetProfileSigningAlgorithmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProfileSigningAlgorithm, true
}

// SetProfileSigningAlgorithm sets field value
func (o *SystemConfigOAuthDto) SetProfileSigningAlgorithm(v string) {
	o.ProfileSigningAlgorithm = v
}

// GetPrompt returns the Prompt field value
func (o *SystemConfigOAuthDto) GetPrompt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prompt, true
}

// SetPrompt sets field value
func (o *SystemConfigOAuthDto) SetPrompt(v string) {
	o.Prompt = v
}

// GetRoleClaim returns the RoleClaim field value
func (o *SystemConfigOAuthDto) GetRoleClaim() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleClaim
}

// GetRoleClaimOk returns a tuple with the RoleClaim field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetRoleClaimOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleClaim, true
}

// SetRoleClaim sets field value
func (o *SystemConfigOAuthDto) SetRoleClaim(v string) {
	o.RoleClaim = v
}

// GetScope returns the Scope field value
func (o *SystemConfigOAuthDto) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *SystemConfigOAuthDto) SetScope(v string) {
	o.Scope = v
}

// GetSigningAlgorithm returns the SigningAlgorithm field value
func (o *SystemConfigOAuthDto) GetSigningAlgorithm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SigningAlgorithm
}

// GetSigningAlgorithmOk returns a tuple with the SigningAlgorithm field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetSigningAlgorithmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SigningAlgorithm, true
}

// SetSigningAlgorithm sets field value
func (o *SystemConfigOAuthDto) SetSigningAlgorithm(v string) {
	o.SigningAlgorithm = v
}

// GetStorageLabelClaim returns the StorageLabelClaim field value
func (o *SystemConfigOAuthDto) GetStorageLabelClaim() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StorageLabelClaim
}

// GetStorageLabelClaimOk returns a tuple with the StorageLabelClaim field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetStorageLabelClaimOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageLabelClaim, true
}

// SetStorageLabelClaim sets field value
func (o *SystemConfigOAuthDto) SetStorageLabelClaim(v string) {
	o.StorageLabelClaim = v
}

// GetStorageQuotaClaim returns the StorageQuotaClaim field value
func (o *SystemConfigOAuthDto) GetStorageQuotaClaim() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StorageQuotaClaim
}

// GetStorageQuotaClaimOk returns a tuple with the StorageQuotaClaim field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetStorageQuotaClaimOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageQuotaClaim, true
}

// SetStorageQuotaClaim sets field value
func (o *SystemConfigOAuthDto) SetStorageQuotaClaim(v string) {
	o.StorageQuotaClaim = v
}

// GetTimeout returns the Timeout field value
func (o *SystemConfigOAuthDto) GetTimeout() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetTimeoutOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timeout, true
}

// SetTimeout sets field value
func (o *SystemConfigOAuthDto) SetTimeout(v int32) {
	o.Timeout = v
}

// GetTokenEndpointAuthMethod returns the TokenEndpointAuthMethod field value
func (o *SystemConfigOAuthDto) GetTokenEndpointAuthMethod() OAuthTokenEndpointAuthMethod {
	if o == nil {
		var ret OAuthTokenEndpointAuthMethod
		return ret
	}

	return o.TokenEndpointAuthMethod
}

// GetTokenEndpointAuthMethodOk returns a tuple with the TokenEndpointAuthMethod field value
// and a boolean to check if the value has been set.
func (o *SystemConfigOAuthDto) GetTokenEndpointAuthMethodOk() (*OAuthTokenEndpointAuthMethod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenEndpointAuthMethod, true
}

// SetTokenEndpointAuthMethod sets field value
func (o *SystemConfigOAuthDto) SetTokenEndpointAuthMethod(v OAuthTokenEndpointAuthMethod) {
	o.TokenEndpointAuthMethod = v
}

func (o SystemConfigOAuthDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemConfigOAuthDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["allowInsecureRequests"] = o.AllowInsecureRequests
	toSerialize["autoLaunch"] = o.AutoLaunch
	toSerialize["autoRegister"] = o.AutoRegister
	toSerialize["buttonText"] = o.ButtonText
	toSerialize["clientId"] = o.ClientId
	toSerialize["clientSecret"] = o.ClientSecret
	toSerialize["defaultStorageQuota"] = o.DefaultStorageQuota.Get()
	toSerialize["enabled"] = o.Enabled
	toSerialize["endSessionEndpoint"] = o.EndSessionEndpoint
	toSerialize["issuerUrl"] = o.IssuerUrl
	toSerialize["mobileOverrideEnabled"] = o.MobileOverrideEnabled
	toSerialize["mobileRedirectUri"] = o.MobileRedirectUri
	toSerialize["profileSigningAlgorithm"] = o.ProfileSigningAlgorithm
	toSerialize["prompt"] = o.Prompt
	toSerialize["roleClaim"] = o.RoleClaim
	toSerialize["scope"] = o.Scope
	toSerialize["signingAlgorithm"] = o.SigningAlgorithm
	toSerialize["storageLabelClaim"] = o.StorageLabelClaim
	toSerialize["storageQuotaClaim"] = o.StorageQuotaClaim
	toSerialize["timeout"] = o.Timeout
	toSerialize["tokenEndpointAuthMethod"] = o.TokenEndpointAuthMethod

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SystemConfigOAuthDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"allowInsecureRequests",
		"autoLaunch",
		"autoRegister",
		"buttonText",
		"clientId",
		"clientSecret",
		"defaultStorageQuota",
		"enabled",
		"endSessionEndpoint",
		"issuerUrl",
		"mobileOverrideEnabled",
		"mobileRedirectUri",
		"profileSigningAlgorithm",
		"prompt",
		"roleClaim",
		"scope",
		"signingAlgorithm",
		"storageLabelClaim",
		"storageQuotaClaim",
		"timeout",
		"tokenEndpointAuthMethod",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemConfigOAuthDto := _SystemConfigOAuthDto{}

	err = json.Unmarshal(data, &varSystemConfigOAuthDto)

	if err != nil {
		return err
	}

	*o = SystemConfigOAuthDto(varSystemConfigOAuthDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "allowInsecureRequests")
		delete(additionalProperties, "autoLaunch")
		delete(additionalProperties, "autoRegister")
		delete(additionalProperties, "buttonText")
		delete(additionalProperties, "clientId")
		delete(additionalProperties, "clientSecret")
		delete(additionalProperties, "defaultStorageQuota")
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "endSessionEndpoint")
		delete(additionalProperties, "issuerUrl")
		delete(additionalProperties, "mobileOverrideEnabled")
		delete(additionalProperties, "mobileRedirectUri")
		delete(additionalProperties, "profileSigningAlgorithm")
		delete(additionalProperties, "prompt")
		delete(additionalProperties, "roleClaim")
		delete(additionalProperties, "scope")
		delete(additionalProperties, "signingAlgorithm")
		delete(additionalProperties, "storageLabelClaim")
		delete(additionalProperties, "storageQuotaClaim")
		delete(additionalProperties, "timeout")
		delete(additionalProperties, "tokenEndpointAuthMethod")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSystemConfigOAuthDto struct {
	value *SystemConfigOAuthDto
	isSet bool
}

func (v NullableSystemConfigOAuthDto) Get() *SystemConfigOAuthDto {
	return v.value
}

func (v *NullableSystemConfigOAuthDto) Set(val *SystemConfigOAuthDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemConfigOAuthDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemConfigOAuthDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemConfigOAuthDto(val *SystemConfigOAuthDto) *NullableSystemConfigOAuthDto {
	return &NullableSystemConfigOAuthDto{value: val, isSet: true}
}

func (v NullableSystemConfigOAuthDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemConfigOAuthDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


