/*
Immich

Immich API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the PluginMethodResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PluginMethodResponseDto{}

// PluginMethodResponseDto struct for PluginMethodResponseDto
type PluginMethodResponseDto struct {
	// Description
	Description string `json:"description"`
	HostFunctions bool `json:"hostFunctions"`
	// Key
	Key string `json:"key"`
	// Name
	Name string `json:"name"`
	Schema map[string]interface{} `json:"schema,omitempty"`
	// Title
	Title string `json:"title"`
	// Workflow types
	Types []WorkflowType `json:"types"`
	// Ui hints
	UiHints []string `json:"uiHints"`
	AdditionalProperties map[string]interface{}
}

type _PluginMethodResponseDto PluginMethodResponseDto

// NewPluginMethodResponseDto instantiates a new PluginMethodResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPluginMethodResponseDto(description string, hostFunctions bool, key string, name string, title string, types []WorkflowType, uiHints []string) *PluginMethodResponseDto {
	this := PluginMethodResponseDto{}
	this.Description = description
	this.HostFunctions = hostFunctions
	this.Key = key
	this.Name = name
	this.Title = title
	this.Types = types
	this.UiHints = uiHints
	return &this
}

// NewPluginMethodResponseDtoWithDefaults instantiates a new PluginMethodResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPluginMethodResponseDtoWithDefaults() *PluginMethodResponseDto {
	this := PluginMethodResponseDto{}
	return &this
}

// GetDescription returns the Description field value
func (o *PluginMethodResponseDto) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *PluginMethodResponseDto) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *PluginMethodResponseDto) SetDescription(v string) {
	o.Description = v
}

// GetHostFunctions returns the HostFunctions field value
func (o *PluginMethodResponseDto) GetHostFunctions() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HostFunctions
}

// GetHostFunctionsOk returns a tuple with the HostFunctions field value
// and a boolean to check if the value has been set.
func (o *PluginMethodResponseDto) GetHostFunctionsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostFunctions, true
}

// SetHostFunctions sets field value
func (o *PluginMethodResponseDto) SetHostFunctions(v bool) {
	o.HostFunctions = v
}

// GetKey returns the Key field value
func (o *PluginMethodResponseDto) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *PluginMethodResponseDto) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *PluginMethodResponseDto) SetKey(v string) {
	o.Key = v
}

// GetName returns the Name field value
func (o *PluginMethodResponseDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PluginMethodResponseDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PluginMethodResponseDto) SetName(v string) {
	o.Name = v
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *PluginMethodResponseDto) GetSchema() map[string]interface{} {
	if o == nil || IsNil(o.Schema) {
		var ret map[string]interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PluginMethodResponseDto) GetSchemaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return map[string]interface{}{}, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *PluginMethodResponseDto) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given map[string]interface{} and assigns it to the Schema field.
func (o *PluginMethodResponseDto) SetSchema(v map[string]interface{}) {
	o.Schema = v
}

// GetTitle returns the Title field value
func (o *PluginMethodResponseDto) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *PluginMethodResponseDto) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *PluginMethodResponseDto) SetTitle(v string) {
	o.Title = v
}

// GetTypes returns the Types field value
func (o *PluginMethodResponseDto) GetTypes() []WorkflowType {
	if o == nil {
		var ret []WorkflowType
		return ret
	}

	return o.Types
}

// GetTypesOk returns a tuple with the Types field value
// and a boolean to check if the value has been set.
func (o *PluginMethodResponseDto) GetTypesOk() ([]WorkflowType, bool) {
	if o == nil {
		return nil, false
	}
	return o.Types, true
}

// SetTypes sets field value
func (o *PluginMethodResponseDto) SetTypes(v []WorkflowType) {
	o.Types = v
}

// GetUiHints returns the UiHints field value
func (o *PluginMethodResponseDto) GetUiHints() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.UiHints
}

// GetUiHintsOk returns a tuple with the UiHints field value
// and a boolean to check if the value has been set.
func (o *PluginMethodResponseDto) GetUiHintsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UiHints, true
}

// SetUiHints sets field value
func (o *PluginMethodResponseDto) SetUiHints(v []string) {
	o.UiHints = v
}

func (o PluginMethodResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PluginMethodResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["hostFunctions"] = o.HostFunctions
	toSerialize["key"] = o.Key
	toSerialize["name"] = o.Name
	if !IsNil(o.Schema) {
		toSerialize["schema"] = o.Schema
	}
	toSerialize["title"] = o.Title
	toSerialize["types"] = o.Types
	toSerialize["uiHints"] = o.UiHints

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PluginMethodResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"hostFunctions",
		"key",
		"name",
		"title",
		"types",
		"uiHints",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPluginMethodResponseDto := _PluginMethodResponseDto{}

	err = json.Unmarshal(data, &varPluginMethodResponseDto)

	if err != nil {
		return err
	}

	*o = PluginMethodResponseDto(varPluginMethodResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "hostFunctions")
		delete(additionalProperties, "key")
		delete(additionalProperties, "name")
		delete(additionalProperties, "schema")
		delete(additionalProperties, "title")
		delete(additionalProperties, "types")
		delete(additionalProperties, "uiHints")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePluginMethodResponseDto struct {
	value *PluginMethodResponseDto
	isSet bool
}

func (v NullablePluginMethodResponseDto) Get() *PluginMethodResponseDto {
	return v.value
}

func (v *NullablePluginMethodResponseDto) Set(val *PluginMethodResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginMethodResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginMethodResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginMethodResponseDto(val *PluginMethodResponseDto) *NullablePluginMethodResponseDto {
	return &NullablePluginMethodResponseDto{value: val, isSet: true}
}

func (v NullablePluginMethodResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginMethodResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


