/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OnboardingResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OnboardingResponseDto{}

// OnboardingResponseDto struct for OnboardingResponseDto
type OnboardingResponseDto struct {
	// Is user onboarded
	IsOnboarded bool `json:"isOnboarded"`
}

type _OnboardingResponseDto OnboardingResponseDto

// NewOnboardingResponseDto instantiates a new OnboardingResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOnboardingResponseDto(isOnboarded bool) *OnboardingResponseDto {
	this := OnboardingResponseDto{}
	this.IsOnboarded = isOnboarded
	return &this
}

// NewOnboardingResponseDtoWithDefaults instantiates a new OnboardingResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOnboardingResponseDtoWithDefaults() *OnboardingResponseDto {
	this := OnboardingResponseDto{}
	return &this
}

// GetIsOnboarded returns the IsOnboarded field value
func (o *OnboardingResponseDto) GetIsOnboarded() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsOnboarded
}

// GetIsOnboardedOk returns a tuple with the IsOnboarded field value
// and a boolean to check if the value has been set.
func (o *OnboardingResponseDto) GetIsOnboardedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsOnboarded, true
}

// SetIsOnboarded sets field value
func (o *OnboardingResponseDto) SetIsOnboarded(v bool) {
	o.IsOnboarded = v
}

func (o OnboardingResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OnboardingResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["isOnboarded"] = o.IsOnboarded
	return toSerialize, nil
}

func (o *OnboardingResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"isOnboarded",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOnboardingResponseDto := _OnboardingResponseDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOnboardingResponseDto)

	if err != nil {
		return err
	}

	*o = OnboardingResponseDto(varOnboardingResponseDto)

	return err
}

type NullableOnboardingResponseDto struct {
	value *OnboardingResponseDto
	isSet bool
}

func (v NullableOnboardingResponseDto) Get() *OnboardingResponseDto {
	return v.value
}

func (v *NullableOnboardingResponseDto) Set(val *OnboardingResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableOnboardingResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableOnboardingResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOnboardingResponseDto(val *OnboardingResponseDto) *NullableOnboardingResponseDto {
	return &NullableOnboardingResponseDto{value: val, isSet: true}
}

func (v NullableOnboardingResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOnboardingResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


