/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobSettingsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobSettingsDto{}

// JobSettingsDto struct for JobSettingsDto
type JobSettingsDto struct {
	// Concurrency
	Concurrency int32 `json:"concurrency"`
}

type _JobSettingsDto JobSettingsDto

// NewJobSettingsDto instantiates a new JobSettingsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobSettingsDto(concurrency int32) *JobSettingsDto {
	this := JobSettingsDto{}
	this.Concurrency = concurrency
	return &this
}

// NewJobSettingsDtoWithDefaults instantiates a new JobSettingsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobSettingsDtoWithDefaults() *JobSettingsDto {
	this := JobSettingsDto{}
	return &this
}

// GetConcurrency returns the Concurrency field value
func (o *JobSettingsDto) GetConcurrency() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Concurrency
}

// GetConcurrencyOk returns a tuple with the Concurrency field value
// and a boolean to check if the value has been set.
func (o *JobSettingsDto) GetConcurrencyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Concurrency, true
}

// SetConcurrency sets field value
func (o *JobSettingsDto) SetConcurrency(v int32) {
	o.Concurrency = v
}

func (o JobSettingsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobSettingsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["concurrency"] = o.Concurrency
	return toSerialize, nil
}

func (o *JobSettingsDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"concurrency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobSettingsDto := _JobSettingsDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobSettingsDto)

	if err != nil {
		return err
	}

	*o = JobSettingsDto(varJobSettingsDto)

	return err
}

type NullableJobSettingsDto struct {
	value *JobSettingsDto
	isSet bool
}

func (v NullableJobSettingsDto) Get() *JobSettingsDto {
	return v.value
}

func (v *NullableJobSettingsDto) Set(val *JobSettingsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableJobSettingsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableJobSettingsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobSettingsDto(val *JobSettingsDto) *NullableJobSettingsDto {
	return &NullableJobSettingsDto{value: val, isSet: true}
}

func (v NullableJobSettingsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobSettingsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


