/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the OAuthConfigDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OAuthConfigDto{}

// OAuthConfigDto struct for OAuthConfigDto
type OAuthConfigDto struct {
	// OAuth code challenge (PKCE)
	CodeChallenge *string `json:"codeChallenge,omitempty"`
	// OAuth redirect URI
	RedirectUri string `json:"redirectUri"`
	// OAuth state parameter
	State *string `json:"state,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OAuthConfigDto OAuthConfigDto

// NewOAuthConfigDto instantiates a new OAuthConfigDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuthConfigDto(redirectUri string) *OAuthConfigDto {
	this := OAuthConfigDto{}
	this.RedirectUri = redirectUri
	return &this
}

// NewOAuthConfigDtoWithDefaults instantiates a new OAuthConfigDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuthConfigDtoWithDefaults() *OAuthConfigDto {
	this := OAuthConfigDto{}
	return &this
}

// GetCodeChallenge returns the CodeChallenge field value if set, zero value otherwise.
func (o *OAuthConfigDto) GetCodeChallenge() string {
	if o == nil || IsNil(o.CodeChallenge) {
		var ret string
		return ret
	}
	return *o.CodeChallenge
}

// GetCodeChallengeOk returns a tuple with the CodeChallenge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthConfigDto) GetCodeChallengeOk() (*string, bool) {
	if o == nil || IsNil(o.CodeChallenge) {
		return nil, false
	}
	return o.CodeChallenge, true
}

// HasCodeChallenge returns a boolean if a field has been set.
func (o *OAuthConfigDto) HasCodeChallenge() bool {
	if o != nil && !IsNil(o.CodeChallenge) {
		return true
	}

	return false
}

// SetCodeChallenge gets a reference to the given string and assigns it to the CodeChallenge field.
func (o *OAuthConfigDto) SetCodeChallenge(v string) {
	o.CodeChallenge = &v
}

// GetRedirectUri returns the RedirectUri field value
func (o *OAuthConfigDto) GetRedirectUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RedirectUri
}

// GetRedirectUriOk returns a tuple with the RedirectUri field value
// and a boolean to check if the value has been set.
func (o *OAuthConfigDto) GetRedirectUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RedirectUri, true
}

// SetRedirectUri sets field value
func (o *OAuthConfigDto) SetRedirectUri(v string) {
	o.RedirectUri = v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *OAuthConfigDto) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthConfigDto) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *OAuthConfigDto) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *OAuthConfigDto) SetState(v string) {
	o.State = &v
}

func (o OAuthConfigDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OAuthConfigDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CodeChallenge) {
		toSerialize["codeChallenge"] = o.CodeChallenge
	}
	toSerialize["redirectUri"] = o.RedirectUri
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OAuthConfigDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"redirectUri",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOAuthConfigDto := _OAuthConfigDto{}

	err = json.Unmarshal(data, &varOAuthConfigDto)

	if err != nil {
		return err
	}

	*o = OAuthConfigDto(varOAuthConfigDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "codeChallenge")
		delete(additionalProperties, "redirectUri")
		delete(additionalProperties, "state")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOAuthConfigDto struct {
	value *OAuthConfigDto
	isSet bool
}

func (v NullableOAuthConfigDto) Get() *OAuthConfigDto {
	return v.value
}

func (v *NullableOAuthConfigDto) Set(val *OAuthConfigDto) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuthConfigDto) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuthConfigDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuthConfigDto(val *OAuthConfigDto) *NullableOAuthConfigDto {
	return &NullableOAuthConfigDto{value: val, isSet: true}
}

func (v NullableOAuthConfigDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuthConfigDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


