/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SyncAlbumUserDeleteV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncAlbumUserDeleteV1{}

// SyncAlbumUserDeleteV1 struct for SyncAlbumUserDeleteV1
type SyncAlbumUserDeleteV1 struct {
	// Album ID
	AlbumId string `json:"albumId"`
	// User ID
	UserId string `json:"userId"`
}

type _SyncAlbumUserDeleteV1 SyncAlbumUserDeleteV1

// NewSyncAlbumUserDeleteV1 instantiates a new SyncAlbumUserDeleteV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncAlbumUserDeleteV1(albumId string, userId string) *SyncAlbumUserDeleteV1 {
	this := SyncAlbumUserDeleteV1{}
	this.AlbumId = albumId
	this.UserId = userId
	return &this
}

// NewSyncAlbumUserDeleteV1WithDefaults instantiates a new SyncAlbumUserDeleteV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncAlbumUserDeleteV1WithDefaults() *SyncAlbumUserDeleteV1 {
	this := SyncAlbumUserDeleteV1{}
	return &this
}

// GetAlbumId returns the AlbumId field value
func (o *SyncAlbumUserDeleteV1) GetAlbumId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AlbumId
}

// GetAlbumIdOk returns a tuple with the AlbumId field value
// and a boolean to check if the value has been set.
func (o *SyncAlbumUserDeleteV1) GetAlbumIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AlbumId, true
}

// SetAlbumId sets field value
func (o *SyncAlbumUserDeleteV1) SetAlbumId(v string) {
	o.AlbumId = v
}

// GetUserId returns the UserId field value
func (o *SyncAlbumUserDeleteV1) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *SyncAlbumUserDeleteV1) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *SyncAlbumUserDeleteV1) SetUserId(v string) {
	o.UserId = v
}

func (o SyncAlbumUserDeleteV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncAlbumUserDeleteV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["albumId"] = o.AlbumId
	toSerialize["userId"] = o.UserId
	return toSerialize, nil
}

func (o *SyncAlbumUserDeleteV1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"albumId",
		"userId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSyncAlbumUserDeleteV1 := _SyncAlbumUserDeleteV1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSyncAlbumUserDeleteV1)

	if err != nil {
		return err
	}

	*o = SyncAlbumUserDeleteV1(varSyncAlbumUserDeleteV1)

	return err
}

type NullableSyncAlbumUserDeleteV1 struct {
	value *SyncAlbumUserDeleteV1
	isSet bool
}

func (v NullableSyncAlbumUserDeleteV1) Get() *SyncAlbumUserDeleteV1 {
	return v.value
}

func (v *NullableSyncAlbumUserDeleteV1) Set(val *SyncAlbumUserDeleteV1) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncAlbumUserDeleteV1) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncAlbumUserDeleteV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncAlbumUserDeleteV1(val *SyncAlbumUserDeleteV1) *NullableSyncAlbumUserDeleteV1 {
	return &NullableSyncAlbumUserDeleteV1{value: val, isSet: true}
}

func (v NullableSyncAlbumUserDeleteV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncAlbumUserDeleteV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


