/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the DatabaseBackupDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DatabaseBackupDto{}

// DatabaseBackupDto struct for DatabaseBackupDto
type DatabaseBackupDto struct {
	// Backup filename
	Filename string `json:"filename"`
	// Backup file size
	Filesize int32 `json:"filesize"`
	// Backup timezone
	Timezone string `json:"timezone"`
	AdditionalProperties map[string]interface{}
}

type _DatabaseBackupDto DatabaseBackupDto

// NewDatabaseBackupDto instantiates a new DatabaseBackupDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatabaseBackupDto(filename string, filesize int32, timezone string) *DatabaseBackupDto {
	this := DatabaseBackupDto{}
	this.Filename = filename
	this.Filesize = filesize
	this.Timezone = timezone
	return &this
}

// NewDatabaseBackupDtoWithDefaults instantiates a new DatabaseBackupDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatabaseBackupDtoWithDefaults() *DatabaseBackupDto {
	this := DatabaseBackupDto{}
	return &this
}

// GetFilename returns the Filename field value
func (o *DatabaseBackupDto) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *DatabaseBackupDto) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *DatabaseBackupDto) SetFilename(v string) {
	o.Filename = v
}

// GetFilesize returns the Filesize field value
func (o *DatabaseBackupDto) GetFilesize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Filesize
}

// GetFilesizeOk returns a tuple with the Filesize field value
// and a boolean to check if the value has been set.
func (o *DatabaseBackupDto) GetFilesizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filesize, true
}

// SetFilesize sets field value
func (o *DatabaseBackupDto) SetFilesize(v int32) {
	o.Filesize = v
}

// GetTimezone returns the Timezone field value
func (o *DatabaseBackupDto) GetTimezone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value
// and a boolean to check if the value has been set.
func (o *DatabaseBackupDto) GetTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timezone, true
}

// SetTimezone sets field value
func (o *DatabaseBackupDto) SetTimezone(v string) {
	o.Timezone = v
}

func (o DatabaseBackupDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DatabaseBackupDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filename"] = o.Filename
	toSerialize["filesize"] = o.Filesize
	toSerialize["timezone"] = o.Timezone

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DatabaseBackupDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"filename",
		"filesize",
		"timezone",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDatabaseBackupDto := _DatabaseBackupDto{}

	err = json.Unmarshal(data, &varDatabaseBackupDto)

	if err != nil {
		return err
	}

	*o = DatabaseBackupDto(varDatabaseBackupDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "filename")
		delete(additionalProperties, "filesize")
		delete(additionalProperties, "timezone")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDatabaseBackupDto struct {
	value *DatabaseBackupDto
	isSet bool
}

func (v NullableDatabaseBackupDto) Get() *DatabaseBackupDto {
	return v.value
}

func (v *NullableDatabaseBackupDto) Set(val *DatabaseBackupDto) {
	v.value = val
	v.isSet = true
}

func (v NullableDatabaseBackupDto) IsSet() bool {
	return v.isSet
}

func (v *NullableDatabaseBackupDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatabaseBackupDto(val *DatabaseBackupDto) *NullableDatabaseBackupDto {
	return &NullableDatabaseBackupDto{value: val, isSet: true}
}

func (v NullableDatabaseBackupDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatabaseBackupDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


