/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// TranscodePolicy Transcode policy
type TranscodePolicy string

// List of TranscodePolicy
const (
	TRANSCODEPOLICY_ALL TranscodePolicy = "all"
	TRANSCODEPOLICY_OPTIMAL TranscodePolicy = "optimal"
	TRANSCODEPOLICY_BITRATE TranscodePolicy = "bitrate"
	TRANSCODEPOLICY_REQUIRED TranscodePolicy = "required"
	TRANSCODEPOLICY_DISABLED TranscodePolicy = "disabled"
)

// All allowed values of TranscodePolicy enum
var AllowedTranscodePolicyEnumValues = []TranscodePolicy{
	"all",
	"optimal",
	"bitrate",
	"required",
	"disabled",
}

func (v *TranscodePolicy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TranscodePolicy(value)
	for _, existing := range AllowedTranscodePolicyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TranscodePolicy", value)
}

// NewTranscodePolicyFromValue returns a pointer to a valid TranscodePolicy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTranscodePolicyFromValue(v string) (*TranscodePolicy, error) {
	ev := TranscodePolicy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TranscodePolicy: valid values are %v", v, AllowedTranscodePolicyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TranscodePolicy) IsValid() bool {
	for _, existing := range AllowedTranscodePolicyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TranscodePolicy value
func (v TranscodePolicy) Ptr() *TranscodePolicy {
	return &v
}

type NullableTranscodePolicy struct {
	value *TranscodePolicy
	isSet bool
}

func (v NullableTranscodePolicy) Get() *TranscodePolicy {
	return v.value
}

func (v *NullableTranscodePolicy) Set(val *TranscodePolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableTranscodePolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableTranscodePolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranscodePolicy(val *TranscodePolicy) *NullableTranscodePolicy {
	return &NullableTranscodePolicy{value: val, isSet: true}
}

func (v NullableTranscodePolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranscodePolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

