/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the AssetBulkUploadCheckDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetBulkUploadCheckDto{}

// AssetBulkUploadCheckDto struct for AssetBulkUploadCheckDto
type AssetBulkUploadCheckDto struct {
	// Assets to check
	Assets []AssetBulkUploadCheckItem `json:"assets"`
	AdditionalProperties map[string]interface{}
}

type _AssetBulkUploadCheckDto AssetBulkUploadCheckDto

// NewAssetBulkUploadCheckDto instantiates a new AssetBulkUploadCheckDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetBulkUploadCheckDto(assets []AssetBulkUploadCheckItem) *AssetBulkUploadCheckDto {
	this := AssetBulkUploadCheckDto{}
	this.Assets = assets
	return &this
}

// NewAssetBulkUploadCheckDtoWithDefaults instantiates a new AssetBulkUploadCheckDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetBulkUploadCheckDtoWithDefaults() *AssetBulkUploadCheckDto {
	this := AssetBulkUploadCheckDto{}
	return &this
}

// GetAssets returns the Assets field value
func (o *AssetBulkUploadCheckDto) GetAssets() []AssetBulkUploadCheckItem {
	if o == nil {
		var ret []AssetBulkUploadCheckItem
		return ret
	}

	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value
// and a boolean to check if the value has been set.
func (o *AssetBulkUploadCheckDto) GetAssetsOk() ([]AssetBulkUploadCheckItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Assets, true
}

// SetAssets sets field value
func (o *AssetBulkUploadCheckDto) SetAssets(v []AssetBulkUploadCheckItem) {
	o.Assets = v
}

func (o AssetBulkUploadCheckDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetBulkUploadCheckDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["assets"] = o.Assets

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AssetBulkUploadCheckDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"assets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssetBulkUploadCheckDto := _AssetBulkUploadCheckDto{}

	err = json.Unmarshal(data, &varAssetBulkUploadCheckDto)

	if err != nil {
		return err
	}

	*o = AssetBulkUploadCheckDto(varAssetBulkUploadCheckDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "assets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAssetBulkUploadCheckDto struct {
	value *AssetBulkUploadCheckDto
	isSet bool
}

func (v NullableAssetBulkUploadCheckDto) Get() *AssetBulkUploadCheckDto {
	return v.value
}

func (v *NullableAssetBulkUploadCheckDto) Set(val *AssetBulkUploadCheckDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetBulkUploadCheckDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetBulkUploadCheckDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetBulkUploadCheckDto(val *AssetBulkUploadCheckDto) *NullableAssetBulkUploadCheckDto {
	return &NullableAssetBulkUploadCheckDto{value: val, isSet: true}
}

func (v NullableAssetBulkUploadCheckDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetBulkUploadCheckDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


