/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SystemConfigNewVersionCheckDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemConfigNewVersionCheckDto{}

// SystemConfigNewVersionCheckDto struct for SystemConfigNewVersionCheckDto
type SystemConfigNewVersionCheckDto struct {
	// Enabled
	Enabled bool `json:"enabled"`
}

type _SystemConfigNewVersionCheckDto SystemConfigNewVersionCheckDto

// NewSystemConfigNewVersionCheckDto instantiates a new SystemConfigNewVersionCheckDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemConfigNewVersionCheckDto(enabled bool) *SystemConfigNewVersionCheckDto {
	this := SystemConfigNewVersionCheckDto{}
	this.Enabled = enabled
	return &this
}

// NewSystemConfigNewVersionCheckDtoWithDefaults instantiates a new SystemConfigNewVersionCheckDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemConfigNewVersionCheckDtoWithDefaults() *SystemConfigNewVersionCheckDto {
	this := SystemConfigNewVersionCheckDto{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *SystemConfigNewVersionCheckDto) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *SystemConfigNewVersionCheckDto) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *SystemConfigNewVersionCheckDto) SetEnabled(v bool) {
	o.Enabled = v
}

func (o SystemConfigNewVersionCheckDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemConfigNewVersionCheckDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	return toSerialize, nil
}

func (o *SystemConfigNewVersionCheckDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemConfigNewVersionCheckDto := _SystemConfigNewVersionCheckDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSystemConfigNewVersionCheckDto)

	if err != nil {
		return err
	}

	*o = SystemConfigNewVersionCheckDto(varSystemConfigNewVersionCheckDto)

	return err
}

type NullableSystemConfigNewVersionCheckDto struct {
	value *SystemConfigNewVersionCheckDto
	isSet bool
}

func (v NullableSystemConfigNewVersionCheckDto) Get() *SystemConfigNewVersionCheckDto {
	return v.value
}

func (v *NullableSystemConfigNewVersionCheckDto) Set(val *SystemConfigNewVersionCheckDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemConfigNewVersionCheckDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemConfigNewVersionCheckDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemConfigNewVersionCheckDto(val *SystemConfigNewVersionCheckDto) *NullableSystemConfigNewVersionCheckDto {
	return &NullableSystemConfigNewVersionCheckDto{value: val, isSet: true}
}

func (v NullableSystemConfigNewVersionCheckDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemConfigNewVersionCheckDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


