/*
Immich

Immich API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the AlbumsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlbumsResponse{}

// AlbumsResponse struct for AlbumsResponse
type AlbumsResponse struct {
	DefaultAssetOrder AssetOrder `json:"defaultAssetOrder"`
	AdditionalProperties map[string]interface{}
}

type _AlbumsResponse AlbumsResponse

// NewAlbumsResponse instantiates a new AlbumsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlbumsResponse(defaultAssetOrder AssetOrder) *AlbumsResponse {
	this := AlbumsResponse{}
	this.DefaultAssetOrder = defaultAssetOrder
	return &this
}

// NewAlbumsResponseWithDefaults instantiates a new AlbumsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlbumsResponseWithDefaults() *AlbumsResponse {
	this := AlbumsResponse{}
	return &this
}

// GetDefaultAssetOrder returns the DefaultAssetOrder field value
func (o *AlbumsResponse) GetDefaultAssetOrder() AssetOrder {
	if o == nil {
		var ret AssetOrder
		return ret
	}

	return o.DefaultAssetOrder
}

// GetDefaultAssetOrderOk returns a tuple with the DefaultAssetOrder field value
// and a boolean to check if the value has been set.
func (o *AlbumsResponse) GetDefaultAssetOrderOk() (*AssetOrder, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultAssetOrder, true
}

// SetDefaultAssetOrder sets field value
func (o *AlbumsResponse) SetDefaultAssetOrder(v AssetOrder) {
	o.DefaultAssetOrder = v
}

func (o AlbumsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlbumsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["defaultAssetOrder"] = o.DefaultAssetOrder

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AlbumsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"defaultAssetOrder",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlbumsResponse := _AlbumsResponse{}

	err = json.Unmarshal(data, &varAlbumsResponse)

	if err != nil {
		return err
	}

	*o = AlbumsResponse(varAlbumsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "defaultAssetOrder")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAlbumsResponse struct {
	value *AlbumsResponse
	isSet bool
}

func (v NullableAlbumsResponse) Get() *AlbumsResponse {
	return v.value
}

func (v *NullableAlbumsResponse) Set(val *AlbumsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlbumsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlbumsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlbumsResponse(val *AlbumsResponse) *NullableAlbumsResponse {
	return &NullableAlbumsResponse{value: val, isSet: true}
}

func (v NullableAlbumsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlbumsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


