/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SyncAlbumV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncAlbumV2{}

// SyncAlbumV2 struct for SyncAlbumV2
type SyncAlbumV2 struct {
	// Created at
	CreatedAt time.Time `json:"createdAt" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
	// Album description
	Description string `json:"description"`
	// Album ID
	Id string `json:"id"`
	// Is activity enabled
	IsActivityEnabled bool `json:"isActivityEnabled"`
	// Album name
	Name string `json:"name"`
	Order AssetOrder `json:"order"`
	// Thumbnail asset ID
	ThumbnailAssetId NullableString `json:"thumbnailAssetId"`
	// Updated at
	UpdatedAt time.Time `json:"updatedAt" validate:"regexp=^(?:(?:\\\\d\\\\d[2468][048]|\\\\d\\\\d[13579][26]|\\\\d\\\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\\\d|30)|(?:02)-(?:0[1-9]|1\\\\d|2[0-8])))T(?:(?:[01]\\\\d|2[0-3]):[0-5]\\\\d(?::[0-5]\\\\d(?:\\\\.\\\\d+)?)?(?:Z))$"`
}

type _SyncAlbumV2 SyncAlbumV2

// NewSyncAlbumV2 instantiates a new SyncAlbumV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncAlbumV2(createdAt time.Time, description string, id string, isActivityEnabled bool, name string, order AssetOrder, thumbnailAssetId NullableString, updatedAt time.Time) *SyncAlbumV2 {
	this := SyncAlbumV2{}
	this.CreatedAt = createdAt
	this.Description = description
	this.Id = id
	this.IsActivityEnabled = isActivityEnabled
	this.Name = name
	this.Order = order
	this.ThumbnailAssetId = thumbnailAssetId
	this.UpdatedAt = updatedAt
	return &this
}

// NewSyncAlbumV2WithDefaults instantiates a new SyncAlbumV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncAlbumV2WithDefaults() *SyncAlbumV2 {
	this := SyncAlbumV2{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *SyncAlbumV2) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SyncAlbumV2) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SyncAlbumV2) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetDescription returns the Description field value
func (o *SyncAlbumV2) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SyncAlbumV2) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SyncAlbumV2) SetDescription(v string) {
	o.Description = v
}

// GetId returns the Id field value
func (o *SyncAlbumV2) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SyncAlbumV2) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SyncAlbumV2) SetId(v string) {
	o.Id = v
}

// GetIsActivityEnabled returns the IsActivityEnabled field value
func (o *SyncAlbumV2) GetIsActivityEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActivityEnabled
}

// GetIsActivityEnabledOk returns a tuple with the IsActivityEnabled field value
// and a boolean to check if the value has been set.
func (o *SyncAlbumV2) GetIsActivityEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActivityEnabled, true
}

// SetIsActivityEnabled sets field value
func (o *SyncAlbumV2) SetIsActivityEnabled(v bool) {
	o.IsActivityEnabled = v
}

// GetName returns the Name field value
func (o *SyncAlbumV2) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SyncAlbumV2) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SyncAlbumV2) SetName(v string) {
	o.Name = v
}

// GetOrder returns the Order field value
func (o *SyncAlbumV2) GetOrder() AssetOrder {
	if o == nil {
		var ret AssetOrder
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *SyncAlbumV2) GetOrderOk() (*AssetOrder, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Order, true
}

// SetOrder sets field value
func (o *SyncAlbumV2) SetOrder(v AssetOrder) {
	o.Order = v
}

// GetThumbnailAssetId returns the ThumbnailAssetId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SyncAlbumV2) GetThumbnailAssetId() string {
	if o == nil || o.ThumbnailAssetId.Get() == nil {
		var ret string
		return ret
	}

	return *o.ThumbnailAssetId.Get()
}

// GetThumbnailAssetIdOk returns a tuple with the ThumbnailAssetId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SyncAlbumV2) GetThumbnailAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ThumbnailAssetId.Get(), o.ThumbnailAssetId.IsSet()
}

// SetThumbnailAssetId sets field value
func (o *SyncAlbumV2) SetThumbnailAssetId(v string) {
	o.ThumbnailAssetId.Set(&v)
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *SyncAlbumV2) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *SyncAlbumV2) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *SyncAlbumV2) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o SyncAlbumV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncAlbumV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["description"] = o.Description
	toSerialize["id"] = o.Id
	toSerialize["isActivityEnabled"] = o.IsActivityEnabled
	toSerialize["name"] = o.Name
	toSerialize["order"] = o.Order
	toSerialize["thumbnailAssetId"] = o.ThumbnailAssetId.Get()
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *SyncAlbumV2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"createdAt",
		"description",
		"id",
		"isActivityEnabled",
		"name",
		"order",
		"thumbnailAssetId",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSyncAlbumV2 := _SyncAlbumV2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSyncAlbumV2)

	if err != nil {
		return err
	}

	*o = SyncAlbumV2(varSyncAlbumV2)

	return err
}

type NullableSyncAlbumV2 struct {
	value *SyncAlbumV2
	isSet bool
}

func (v NullableSyncAlbumV2) Get() *SyncAlbumV2 {
	return v.value
}

func (v *NullableSyncAlbumV2) Set(val *SyncAlbumV2) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncAlbumV2) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncAlbumV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncAlbumV2(val *SyncAlbumV2) *NullableSyncAlbumV2 {
	return &NullableSyncAlbumV2{value: val, isSet: true}
}

func (v NullableSyncAlbumV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncAlbumV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


