/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TagBulkAssetsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagBulkAssetsDto{}

// TagBulkAssetsDto struct for TagBulkAssetsDto
type TagBulkAssetsDto struct {
	// Asset IDs
	AssetIds []string `json:"assetIds"`
	// Tag IDs
	TagIds []string `json:"tagIds"`
}

type _TagBulkAssetsDto TagBulkAssetsDto

// NewTagBulkAssetsDto instantiates a new TagBulkAssetsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagBulkAssetsDto(assetIds []string, tagIds []string) *TagBulkAssetsDto {
	this := TagBulkAssetsDto{}
	this.AssetIds = assetIds
	this.TagIds = tagIds
	return &this
}

// NewTagBulkAssetsDtoWithDefaults instantiates a new TagBulkAssetsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagBulkAssetsDtoWithDefaults() *TagBulkAssetsDto {
	this := TagBulkAssetsDto{}
	return &this
}

// GetAssetIds returns the AssetIds field value
func (o *TagBulkAssetsDto) GetAssetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AssetIds
}

// GetAssetIdsOk returns a tuple with the AssetIds field value
// and a boolean to check if the value has been set.
func (o *TagBulkAssetsDto) GetAssetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssetIds, true
}

// SetAssetIds sets field value
func (o *TagBulkAssetsDto) SetAssetIds(v []string) {
	o.AssetIds = v
}

// GetTagIds returns the TagIds field value
func (o *TagBulkAssetsDto) GetTagIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.TagIds
}

// GetTagIdsOk returns a tuple with the TagIds field value
// and a boolean to check if the value has been set.
func (o *TagBulkAssetsDto) GetTagIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TagIds, true
}

// SetTagIds sets field value
func (o *TagBulkAssetsDto) SetTagIds(v []string) {
	o.TagIds = v
}

func (o TagBulkAssetsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagBulkAssetsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["assetIds"] = o.AssetIds
	toSerialize["tagIds"] = o.TagIds
	return toSerialize, nil
}

func (o *TagBulkAssetsDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"assetIds",
		"tagIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTagBulkAssetsDto := _TagBulkAssetsDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTagBulkAssetsDto)

	if err != nil {
		return err
	}

	*o = TagBulkAssetsDto(varTagBulkAssetsDto)

	return err
}

type NullableTagBulkAssetsDto struct {
	value *TagBulkAssetsDto
	isSet bool
}

func (v NullableTagBulkAssetsDto) Get() *TagBulkAssetsDto {
	return v.value
}

func (v *NullableTagBulkAssetsDto) Set(val *TagBulkAssetsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTagBulkAssetsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTagBulkAssetsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagBulkAssetsDto(val *TagBulkAssetsDto) *NullableTagBulkAssetsDto {
	return &NullableTagBulkAssetsDto{value: val, isSet: true}
}

func (v NullableTagBulkAssetsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagBulkAssetsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


