/*
Immich

Immich API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the SystemConfigImageDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemConfigImageDto{}

// SystemConfigImageDto struct for SystemConfigImageDto
type SystemConfigImageDto struct {
	Colorspace Colorspace `json:"colorspace"`
	// Extract embedded
	ExtractEmbedded bool `json:"extractEmbedded"`
	Fullsize SystemConfigGeneratedFullsizeImageDto `json:"fullsize"`
	Preview SystemConfigGeneratedImageDto `json:"preview"`
	Thumbnail SystemConfigGeneratedImageDto `json:"thumbnail"`
	AdditionalProperties map[string]interface{}
}

type _SystemConfigImageDto SystemConfigImageDto

// NewSystemConfigImageDto instantiates a new SystemConfigImageDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemConfigImageDto(colorspace Colorspace, extractEmbedded bool, fullsize SystemConfigGeneratedFullsizeImageDto, preview SystemConfigGeneratedImageDto, thumbnail SystemConfigGeneratedImageDto) *SystemConfigImageDto {
	this := SystemConfigImageDto{}
	this.Colorspace = colorspace
	this.ExtractEmbedded = extractEmbedded
	this.Fullsize = fullsize
	this.Preview = preview
	this.Thumbnail = thumbnail
	return &this
}

// NewSystemConfigImageDtoWithDefaults instantiates a new SystemConfigImageDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemConfigImageDtoWithDefaults() *SystemConfigImageDto {
	this := SystemConfigImageDto{}
	return &this
}

// GetColorspace returns the Colorspace field value
func (o *SystemConfigImageDto) GetColorspace() Colorspace {
	if o == nil {
		var ret Colorspace
		return ret
	}

	return o.Colorspace
}

// GetColorspaceOk returns a tuple with the Colorspace field value
// and a boolean to check if the value has been set.
func (o *SystemConfigImageDto) GetColorspaceOk() (*Colorspace, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Colorspace, true
}

// SetColorspace sets field value
func (o *SystemConfigImageDto) SetColorspace(v Colorspace) {
	o.Colorspace = v
}

// GetExtractEmbedded returns the ExtractEmbedded field value
func (o *SystemConfigImageDto) GetExtractEmbedded() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ExtractEmbedded
}

// GetExtractEmbeddedOk returns a tuple with the ExtractEmbedded field value
// and a boolean to check if the value has been set.
func (o *SystemConfigImageDto) GetExtractEmbeddedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExtractEmbedded, true
}

// SetExtractEmbedded sets field value
func (o *SystemConfigImageDto) SetExtractEmbedded(v bool) {
	o.ExtractEmbedded = v
}

// GetFullsize returns the Fullsize field value
func (o *SystemConfigImageDto) GetFullsize() SystemConfigGeneratedFullsizeImageDto {
	if o == nil {
		var ret SystemConfigGeneratedFullsizeImageDto
		return ret
	}

	return o.Fullsize
}

// GetFullsizeOk returns a tuple with the Fullsize field value
// and a boolean to check if the value has been set.
func (o *SystemConfigImageDto) GetFullsizeOk() (*SystemConfigGeneratedFullsizeImageDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fullsize, true
}

// SetFullsize sets field value
func (o *SystemConfigImageDto) SetFullsize(v SystemConfigGeneratedFullsizeImageDto) {
	o.Fullsize = v
}

// GetPreview returns the Preview field value
func (o *SystemConfigImageDto) GetPreview() SystemConfigGeneratedImageDto {
	if o == nil {
		var ret SystemConfigGeneratedImageDto
		return ret
	}

	return o.Preview
}

// GetPreviewOk returns a tuple with the Preview field value
// and a boolean to check if the value has been set.
func (o *SystemConfigImageDto) GetPreviewOk() (*SystemConfigGeneratedImageDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Preview, true
}

// SetPreview sets field value
func (o *SystemConfigImageDto) SetPreview(v SystemConfigGeneratedImageDto) {
	o.Preview = v
}

// GetThumbnail returns the Thumbnail field value
func (o *SystemConfigImageDto) GetThumbnail() SystemConfigGeneratedImageDto {
	if o == nil {
		var ret SystemConfigGeneratedImageDto
		return ret
	}

	return o.Thumbnail
}

// GetThumbnailOk returns a tuple with the Thumbnail field value
// and a boolean to check if the value has been set.
func (o *SystemConfigImageDto) GetThumbnailOk() (*SystemConfigGeneratedImageDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Thumbnail, true
}

// SetThumbnail sets field value
func (o *SystemConfigImageDto) SetThumbnail(v SystemConfigGeneratedImageDto) {
	o.Thumbnail = v
}

func (o SystemConfigImageDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemConfigImageDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["colorspace"] = o.Colorspace
	toSerialize["extractEmbedded"] = o.ExtractEmbedded
	toSerialize["fullsize"] = o.Fullsize
	toSerialize["preview"] = o.Preview
	toSerialize["thumbnail"] = o.Thumbnail

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SystemConfigImageDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"colorspace",
		"extractEmbedded",
		"fullsize",
		"preview",
		"thumbnail",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemConfigImageDto := _SystemConfigImageDto{}

	err = json.Unmarshal(data, &varSystemConfigImageDto)

	if err != nil {
		return err
	}

	*o = SystemConfigImageDto(varSystemConfigImageDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "colorspace")
		delete(additionalProperties, "extractEmbedded")
		delete(additionalProperties, "fullsize")
		delete(additionalProperties, "preview")
		delete(additionalProperties, "thumbnail")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSystemConfigImageDto struct {
	value *SystemConfigImageDto
	isSet bool
}

func (v NullableSystemConfigImageDto) Get() *SystemConfigImageDto {
	return v.value
}

func (v *NullableSystemConfigImageDto) Set(val *SystemConfigImageDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemConfigImageDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemConfigImageDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemConfigImageDto(val *SystemConfigImageDto) *NullableSystemConfigImageDto {
	return &NullableSystemConfigImageDto{value: val, isSet: true}
}

func (v NullableSystemConfigImageDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemConfigImageDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


