/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// AssetVisibility Asset visibility
type AssetVisibility string

// List of AssetVisibility
const (
	ASSETVISIBILITY_ARCHIVE AssetVisibility = "archive"
	ASSETVISIBILITY_TIMELINE AssetVisibility = "timeline"
	ASSETVISIBILITY_HIDDEN AssetVisibility = "hidden"
	ASSETVISIBILITY_LOCKED AssetVisibility = "locked"
)

// All allowed values of AssetVisibility enum
var AllowedAssetVisibilityEnumValues = []AssetVisibility{
	"archive",
	"timeline",
	"hidden",
	"locked",
}

func (v *AssetVisibility) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AssetVisibility(value)
	for _, existing := range AllowedAssetVisibilityEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AssetVisibility", value)
}

// NewAssetVisibilityFromValue returns a pointer to a valid AssetVisibility
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAssetVisibilityFromValue(v string) (*AssetVisibility, error) {
	ev := AssetVisibility(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AssetVisibility: valid values are %v", v, AllowedAssetVisibilityEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AssetVisibility) IsValid() bool {
	for _, existing := range AllowedAssetVisibilityEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AssetVisibility value
func (v AssetVisibility) Ptr() *AssetVisibility {
	return &v
}

type NullableAssetVisibility struct {
	value *AssetVisibility
	isSet bool
}

func (v NullableAssetVisibility) Get() *AssetVisibility {
	return v.value
}

func (v *NullableAssetVisibility) Set(val *AssetVisibility) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetVisibility) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetVisibility) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetVisibility(val *AssetVisibility) *NullableAssetVisibility {
	return &NullableAssetVisibility{value: val, isSet: true}
}

func (v NullableAssetVisibility) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetVisibility) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

