/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
)

// checks if the SessionCreateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionCreateDto{}

// SessionCreateDto struct for SessionCreateDto
type SessionCreateDto struct {
	// Device OS
	DeviceOS *string `json:"deviceOS,omitempty"`
	// Device type
	DeviceType *string `json:"deviceType,omitempty"`
	// Session duration in seconds
	Duration *int32 `json:"duration,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SessionCreateDto SessionCreateDto

// NewSessionCreateDto instantiates a new SessionCreateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionCreateDto() *SessionCreateDto {
	this := SessionCreateDto{}
	return &this
}

// NewSessionCreateDtoWithDefaults instantiates a new SessionCreateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionCreateDtoWithDefaults() *SessionCreateDto {
	this := SessionCreateDto{}
	return &this
}

// GetDeviceOS returns the DeviceOS field value if set, zero value otherwise.
func (o *SessionCreateDto) GetDeviceOS() string {
	if o == nil || IsNil(o.DeviceOS) {
		var ret string
		return ret
	}
	return *o.DeviceOS
}

// GetDeviceOSOk returns a tuple with the DeviceOS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCreateDto) GetDeviceOSOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceOS) {
		return nil, false
	}
	return o.DeviceOS, true
}

// HasDeviceOS returns a boolean if a field has been set.
func (o *SessionCreateDto) HasDeviceOS() bool {
	if o != nil && !IsNil(o.DeviceOS) {
		return true
	}

	return false
}

// SetDeviceOS gets a reference to the given string and assigns it to the DeviceOS field.
func (o *SessionCreateDto) SetDeviceOS(v string) {
	o.DeviceOS = &v
}

// GetDeviceType returns the DeviceType field value if set, zero value otherwise.
func (o *SessionCreateDto) GetDeviceType() string {
	if o == nil || IsNil(o.DeviceType) {
		var ret string
		return ret
	}
	return *o.DeviceType
}

// GetDeviceTypeOk returns a tuple with the DeviceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCreateDto) GetDeviceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceType) {
		return nil, false
	}
	return o.DeviceType, true
}

// HasDeviceType returns a boolean if a field has been set.
func (o *SessionCreateDto) HasDeviceType() bool {
	if o != nil && !IsNil(o.DeviceType) {
		return true
	}

	return false
}

// SetDeviceType gets a reference to the given string and assigns it to the DeviceType field.
func (o *SessionCreateDto) SetDeviceType(v string) {
	o.DeviceType = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *SessionCreateDto) GetDuration() int32 {
	if o == nil || IsNil(o.Duration) {
		var ret int32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCreateDto) GetDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *SessionCreateDto) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int32 and assigns it to the Duration field.
func (o *SessionCreateDto) SetDuration(v int32) {
	o.Duration = &v
}

func (o SessionCreateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionCreateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceOS) {
		toSerialize["deviceOS"] = o.DeviceOS
	}
	if !IsNil(o.DeviceType) {
		toSerialize["deviceType"] = o.DeviceType
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SessionCreateDto) UnmarshalJSON(data []byte) (err error) {
	varSessionCreateDto := _SessionCreateDto{}

	err = json.Unmarshal(data, &varSessionCreateDto)

	if err != nil {
		return err
	}

	*o = SessionCreateDto(varSessionCreateDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "deviceOS")
		delete(additionalProperties, "deviceType")
		delete(additionalProperties, "duration")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSessionCreateDto struct {
	value *SessionCreateDto
	isSet bool
}

func (v NullableSessionCreateDto) Get() *SessionCreateDto {
	return v.value
}

func (v *NullableSessionCreateDto) Set(val *SessionCreateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionCreateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionCreateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionCreateDto(val *SessionCreateDto) *NullableSessionCreateDto {
	return &NullableSessionCreateDto{value: val, isSet: true}
}

func (v NullableSessionCreateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionCreateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


