/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// BulkIdErrorReason Error reason
type BulkIdErrorReason string

// List of BulkIdErrorReason
const (
	BULKIDERRORREASON_DUPLICATE BulkIdErrorReason = "duplicate"
	BULKIDERRORREASON_NO_PERMISSION BulkIdErrorReason = "no_permission"
	BULKIDERRORREASON_NOT_FOUND BulkIdErrorReason = "not_found"
	BULKIDERRORREASON_UNKNOWN BulkIdErrorReason = "unknown"
	BULKIDERRORREASON_VALIDATION BulkIdErrorReason = "validation"
)

// All allowed values of BulkIdErrorReason enum
var AllowedBulkIdErrorReasonEnumValues = []BulkIdErrorReason{
	"duplicate",
	"no_permission",
	"not_found",
	"unknown",
	"validation",
}

func (v *BulkIdErrorReason) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkIdErrorReason(value)
	for _, existing := range AllowedBulkIdErrorReasonEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkIdErrorReason", value)
}

// NewBulkIdErrorReasonFromValue returns a pointer to a valid BulkIdErrorReason
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkIdErrorReasonFromValue(v string) (*BulkIdErrorReason, error) {
	ev := BulkIdErrorReason(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkIdErrorReason: valid values are %v", v, AllowedBulkIdErrorReasonEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkIdErrorReason) IsValid() bool {
	for _, existing := range AllowedBulkIdErrorReasonEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkIdErrorReason value
func (v BulkIdErrorReason) Ptr() *BulkIdErrorReason {
	return &v
}

type NullableBulkIdErrorReason struct {
	value *BulkIdErrorReason
	isSet bool
}

func (v NullableBulkIdErrorReason) Get() *BulkIdErrorReason {
	return v.value
}

func (v *NullableBulkIdErrorReason) Set(val *BulkIdErrorReason) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkIdErrorReason) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkIdErrorReason) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkIdErrorReason(val *BulkIdErrorReason) *NullableBulkIdErrorReason {
	return &NullableBulkIdErrorReason{value: val, isSet: true}
}

func (v NullableBulkIdErrorReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkIdErrorReason) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

