/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SystemConfigTemplatesDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemConfigTemplatesDto{}

// SystemConfigTemplatesDto struct for SystemConfigTemplatesDto
type SystemConfigTemplatesDto struct {
	Email SystemConfigTemplateEmailsDto `json:"email"`
}

type _SystemConfigTemplatesDto SystemConfigTemplatesDto

// NewSystemConfigTemplatesDto instantiates a new SystemConfigTemplatesDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemConfigTemplatesDto(email SystemConfigTemplateEmailsDto) *SystemConfigTemplatesDto {
	this := SystemConfigTemplatesDto{}
	this.Email = email
	return &this
}

// NewSystemConfigTemplatesDtoWithDefaults instantiates a new SystemConfigTemplatesDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemConfigTemplatesDtoWithDefaults() *SystemConfigTemplatesDto {
	this := SystemConfigTemplatesDto{}
	return &this
}

// GetEmail returns the Email field value
func (o *SystemConfigTemplatesDto) GetEmail() SystemConfigTemplateEmailsDto {
	if o == nil {
		var ret SystemConfigTemplateEmailsDto
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *SystemConfigTemplatesDto) GetEmailOk() (*SystemConfigTemplateEmailsDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *SystemConfigTemplatesDto) SetEmail(v SystemConfigTemplateEmailsDto) {
	o.Email = v
}

func (o SystemConfigTemplatesDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemConfigTemplatesDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *SystemConfigTemplatesDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemConfigTemplatesDto := _SystemConfigTemplatesDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSystemConfigTemplatesDto)

	if err != nil {
		return err
	}

	*o = SystemConfigTemplatesDto(varSystemConfigTemplatesDto)

	return err
}

type NullableSystemConfigTemplatesDto struct {
	value *SystemConfigTemplatesDto
	isSet bool
}

func (v NullableSystemConfigTemplatesDto) Get() *SystemConfigTemplatesDto {
	return v.value
}

func (v *NullableSystemConfigTemplatesDto) Set(val *SystemConfigTemplatesDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemConfigTemplatesDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemConfigTemplatesDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemConfigTemplatesDto(val *SystemConfigTemplatesDto) *NullableSystemConfigTemplatesDto {
	return &NullableSystemConfigTemplatesDto{value: val, isSet: true}
}

func (v NullableSystemConfigTemplatesDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemConfigTemplatesDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


