/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
)

// checks if the SyncAckDeleteDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncAckDeleteDto{}

// SyncAckDeleteDto struct for SyncAckDeleteDto
type SyncAckDeleteDto struct {
	// Sync entity types to delete acks for
	Types []SyncEntityType `json:"types,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SyncAckDeleteDto SyncAckDeleteDto

// NewSyncAckDeleteDto instantiates a new SyncAckDeleteDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncAckDeleteDto() *SyncAckDeleteDto {
	this := SyncAckDeleteDto{}
	return &this
}

// NewSyncAckDeleteDtoWithDefaults instantiates a new SyncAckDeleteDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncAckDeleteDtoWithDefaults() *SyncAckDeleteDto {
	this := SyncAckDeleteDto{}
	return &this
}

// GetTypes returns the Types field value if set, zero value otherwise.
func (o *SyncAckDeleteDto) GetTypes() []SyncEntityType {
	if o == nil || IsNil(o.Types) {
		var ret []SyncEntityType
		return ret
	}
	return o.Types
}

// GetTypesOk returns a tuple with the Types field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncAckDeleteDto) GetTypesOk() ([]SyncEntityType, bool) {
	if o == nil || IsNil(o.Types) {
		return nil, false
	}
	return o.Types, true
}

// HasTypes returns a boolean if a field has been set.
func (o *SyncAckDeleteDto) HasTypes() bool {
	if o != nil && !IsNil(o.Types) {
		return true
	}

	return false
}

// SetTypes gets a reference to the given []SyncEntityType and assigns it to the Types field.
func (o *SyncAckDeleteDto) SetTypes(v []SyncEntityType) {
	o.Types = v
}

func (o SyncAckDeleteDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncAckDeleteDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Types) {
		toSerialize["types"] = o.Types
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SyncAckDeleteDto) UnmarshalJSON(data []byte) (err error) {
	varSyncAckDeleteDto := _SyncAckDeleteDto{}

	err = json.Unmarshal(data, &varSyncAckDeleteDto)

	if err != nil {
		return err
	}

	*o = SyncAckDeleteDto(varSyncAckDeleteDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "types")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSyncAckDeleteDto struct {
	value *SyncAckDeleteDto
	isSet bool
}

func (v NullableSyncAckDeleteDto) Get() *SyncAckDeleteDto {
	return v.value
}

func (v *NullableSyncAckDeleteDto) Set(val *SyncAckDeleteDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncAckDeleteDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncAckDeleteDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncAckDeleteDto(val *SyncAckDeleteDto) *NullableSyncAckDeleteDto {
	return &NullableSyncAckDeleteDto{value: val, isSet: true}
}

func (v NullableSyncAckDeleteDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncAckDeleteDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


