/*
Immich

Immich API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the DuplicateResolveGroupDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DuplicateResolveGroupDto{}

// DuplicateResolveGroupDto struct for DuplicateResolveGroupDto
type DuplicateResolveGroupDto struct {
	DuplicateId string `json:"duplicateId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$"`
	// Asset IDs to keep
	KeepAssetIds []string `json:"keepAssetIds"`
	// Asset IDs to trash or delete
	TrashAssetIds []string `json:"trashAssetIds"`
	AdditionalProperties map[string]interface{}
}

type _DuplicateResolveGroupDto DuplicateResolveGroupDto

// NewDuplicateResolveGroupDto instantiates a new DuplicateResolveGroupDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDuplicateResolveGroupDto(duplicateId string, keepAssetIds []string, trashAssetIds []string) *DuplicateResolveGroupDto {
	this := DuplicateResolveGroupDto{}
	this.DuplicateId = duplicateId
	this.KeepAssetIds = keepAssetIds
	this.TrashAssetIds = trashAssetIds
	return &this
}

// NewDuplicateResolveGroupDtoWithDefaults instantiates a new DuplicateResolveGroupDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDuplicateResolveGroupDtoWithDefaults() *DuplicateResolveGroupDto {
	this := DuplicateResolveGroupDto{}
	return &this
}

// GetDuplicateId returns the DuplicateId field value
func (o *DuplicateResolveGroupDto) GetDuplicateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DuplicateId
}

// GetDuplicateIdOk returns a tuple with the DuplicateId field value
// and a boolean to check if the value has been set.
func (o *DuplicateResolveGroupDto) GetDuplicateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DuplicateId, true
}

// SetDuplicateId sets field value
func (o *DuplicateResolveGroupDto) SetDuplicateId(v string) {
	o.DuplicateId = v
}

// GetKeepAssetIds returns the KeepAssetIds field value
func (o *DuplicateResolveGroupDto) GetKeepAssetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.KeepAssetIds
}

// GetKeepAssetIdsOk returns a tuple with the KeepAssetIds field value
// and a boolean to check if the value has been set.
func (o *DuplicateResolveGroupDto) GetKeepAssetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.KeepAssetIds, true
}

// SetKeepAssetIds sets field value
func (o *DuplicateResolveGroupDto) SetKeepAssetIds(v []string) {
	o.KeepAssetIds = v
}

// GetTrashAssetIds returns the TrashAssetIds field value
func (o *DuplicateResolveGroupDto) GetTrashAssetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.TrashAssetIds
}

// GetTrashAssetIdsOk returns a tuple with the TrashAssetIds field value
// and a boolean to check if the value has been set.
func (o *DuplicateResolveGroupDto) GetTrashAssetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrashAssetIds, true
}

// SetTrashAssetIds sets field value
func (o *DuplicateResolveGroupDto) SetTrashAssetIds(v []string) {
	o.TrashAssetIds = v
}

func (o DuplicateResolveGroupDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DuplicateResolveGroupDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["duplicateId"] = o.DuplicateId
	toSerialize["keepAssetIds"] = o.KeepAssetIds
	toSerialize["trashAssetIds"] = o.TrashAssetIds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DuplicateResolveGroupDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"duplicateId",
		"keepAssetIds",
		"trashAssetIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDuplicateResolveGroupDto := _DuplicateResolveGroupDto{}

	err = json.Unmarshal(data, &varDuplicateResolveGroupDto)

	if err != nil {
		return err
	}

	*o = DuplicateResolveGroupDto(varDuplicateResolveGroupDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "duplicateId")
		delete(additionalProperties, "keepAssetIds")
		delete(additionalProperties, "trashAssetIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDuplicateResolveGroupDto struct {
	value *DuplicateResolveGroupDto
	isSet bool
}

func (v NullableDuplicateResolveGroupDto) Get() *DuplicateResolveGroupDto {
	return v.value
}

func (v *NullableDuplicateResolveGroupDto) Set(val *DuplicateResolveGroupDto) {
	v.value = val
	v.isSet = true
}

func (v NullableDuplicateResolveGroupDto) IsSet() bool {
	return v.isSet
}

func (v *NullableDuplicateResolveGroupDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDuplicateResolveGroupDto(val *DuplicateResolveGroupDto) *NullableDuplicateResolveGroupDto {
	return &NullableDuplicateResolveGroupDto{value: val, isSet: true}
}

func (v NullableDuplicateResolveGroupDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDuplicateResolveGroupDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


