/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the TagBulkAssetsResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagBulkAssetsResponseDto{}

// TagBulkAssetsResponseDto struct for TagBulkAssetsResponseDto
type TagBulkAssetsResponseDto struct {
	// Number of assets tagged
	Count int32 `json:"count"`
	AdditionalProperties map[string]interface{}
}

type _TagBulkAssetsResponseDto TagBulkAssetsResponseDto

// NewTagBulkAssetsResponseDto instantiates a new TagBulkAssetsResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagBulkAssetsResponseDto(count int32) *TagBulkAssetsResponseDto {
	this := TagBulkAssetsResponseDto{}
	this.Count = count
	return &this
}

// NewTagBulkAssetsResponseDtoWithDefaults instantiates a new TagBulkAssetsResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagBulkAssetsResponseDtoWithDefaults() *TagBulkAssetsResponseDto {
	this := TagBulkAssetsResponseDto{}
	return &this
}

// GetCount returns the Count field value
func (o *TagBulkAssetsResponseDto) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *TagBulkAssetsResponseDto) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *TagBulkAssetsResponseDto) SetCount(v int32) {
	o.Count = v
}

func (o TagBulkAssetsResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagBulkAssetsResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TagBulkAssetsResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTagBulkAssetsResponseDto := _TagBulkAssetsResponseDto{}

	err = json.Unmarshal(data, &varTagBulkAssetsResponseDto)

	if err != nil {
		return err
	}

	*o = TagBulkAssetsResponseDto(varTagBulkAssetsResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTagBulkAssetsResponseDto struct {
	value *TagBulkAssetsResponseDto
	isSet bool
}

func (v NullableTagBulkAssetsResponseDto) Get() *TagBulkAssetsResponseDto {
	return v.value
}

func (v *NullableTagBulkAssetsResponseDto) Set(val *TagBulkAssetsResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTagBulkAssetsResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTagBulkAssetsResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagBulkAssetsResponseDto(val *TagBulkAssetsResponseDto) *NullableTagBulkAssetsResponseDto {
	return &NullableTagBulkAssetsResponseDto{value: val, isSet: true}
}

func (v NullableTagBulkAssetsResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagBulkAssetsResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


