/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SystemConfigNotificationsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemConfigNotificationsDto{}

// SystemConfigNotificationsDto struct for SystemConfigNotificationsDto
type SystemConfigNotificationsDto struct {
	Smtp SystemConfigSmtpDto `json:"smtp"`
}

type _SystemConfigNotificationsDto SystemConfigNotificationsDto

// NewSystemConfigNotificationsDto instantiates a new SystemConfigNotificationsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemConfigNotificationsDto(smtp SystemConfigSmtpDto) *SystemConfigNotificationsDto {
	this := SystemConfigNotificationsDto{}
	this.Smtp = smtp
	return &this
}

// NewSystemConfigNotificationsDtoWithDefaults instantiates a new SystemConfigNotificationsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemConfigNotificationsDtoWithDefaults() *SystemConfigNotificationsDto {
	this := SystemConfigNotificationsDto{}
	return &this
}

// GetSmtp returns the Smtp field value
func (o *SystemConfigNotificationsDto) GetSmtp() SystemConfigSmtpDto {
	if o == nil {
		var ret SystemConfigSmtpDto
		return ret
	}

	return o.Smtp
}

// GetSmtpOk returns a tuple with the Smtp field value
// and a boolean to check if the value has been set.
func (o *SystemConfigNotificationsDto) GetSmtpOk() (*SystemConfigSmtpDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Smtp, true
}

// SetSmtp sets field value
func (o *SystemConfigNotificationsDto) SetSmtp(v SystemConfigSmtpDto) {
	o.Smtp = v
}

func (o SystemConfigNotificationsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemConfigNotificationsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["smtp"] = o.Smtp
	return toSerialize, nil
}

func (o *SystemConfigNotificationsDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"smtp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemConfigNotificationsDto := _SystemConfigNotificationsDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSystemConfigNotificationsDto)

	if err != nil {
		return err
	}

	*o = SystemConfigNotificationsDto(varSystemConfigNotificationsDto)

	return err
}

type NullableSystemConfigNotificationsDto struct {
	value *SystemConfigNotificationsDto
	isSet bool
}

func (v NullableSystemConfigNotificationsDto) Get() *SystemConfigNotificationsDto {
	return v.value
}

func (v *NullableSystemConfigNotificationsDto) Set(val *SystemConfigNotificationsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemConfigNotificationsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemConfigNotificationsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemConfigNotificationsDto(val *SystemConfigNotificationsDto) *NullableSystemConfigNotificationsDto {
	return &NullableSystemConfigNotificationsDto{value: val, isSet: true}
}

func (v NullableSystemConfigNotificationsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemConfigNotificationsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


