/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
)

// checks if the PurchaseUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PurchaseUpdate{}

// PurchaseUpdate struct for PurchaseUpdate
type PurchaseUpdate struct {
	// Date until which to hide buy button
	HideBuyButtonUntil *string `json:"hideBuyButtonUntil,omitempty"`
	// Whether to show support badge
	ShowSupportBadge *bool `json:"showSupportBadge,omitempty"`
}

// NewPurchaseUpdate instantiates a new PurchaseUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPurchaseUpdate() *PurchaseUpdate {
	this := PurchaseUpdate{}
	return &this
}

// NewPurchaseUpdateWithDefaults instantiates a new PurchaseUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPurchaseUpdateWithDefaults() *PurchaseUpdate {
	this := PurchaseUpdate{}
	return &this
}

// GetHideBuyButtonUntil returns the HideBuyButtonUntil field value if set, zero value otherwise.
func (o *PurchaseUpdate) GetHideBuyButtonUntil() string {
	if o == nil || IsNil(o.HideBuyButtonUntil) {
		var ret string
		return ret
	}
	return *o.HideBuyButtonUntil
}

// GetHideBuyButtonUntilOk returns a tuple with the HideBuyButtonUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseUpdate) GetHideBuyButtonUntilOk() (*string, bool) {
	if o == nil || IsNil(o.HideBuyButtonUntil) {
		return nil, false
	}
	return o.HideBuyButtonUntil, true
}

// HasHideBuyButtonUntil returns a boolean if a field has been set.
func (o *PurchaseUpdate) HasHideBuyButtonUntil() bool {
	if o != nil && !IsNil(o.HideBuyButtonUntil) {
		return true
	}

	return false
}

// SetHideBuyButtonUntil gets a reference to the given string and assigns it to the HideBuyButtonUntil field.
func (o *PurchaseUpdate) SetHideBuyButtonUntil(v string) {
	o.HideBuyButtonUntil = &v
}

// GetShowSupportBadge returns the ShowSupportBadge field value if set, zero value otherwise.
func (o *PurchaseUpdate) GetShowSupportBadge() bool {
	if o == nil || IsNil(o.ShowSupportBadge) {
		var ret bool
		return ret
	}
	return *o.ShowSupportBadge
}

// GetShowSupportBadgeOk returns a tuple with the ShowSupportBadge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseUpdate) GetShowSupportBadgeOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowSupportBadge) {
		return nil, false
	}
	return o.ShowSupportBadge, true
}

// HasShowSupportBadge returns a boolean if a field has been set.
func (o *PurchaseUpdate) HasShowSupportBadge() bool {
	if o != nil && !IsNil(o.ShowSupportBadge) {
		return true
	}

	return false
}

// SetShowSupportBadge gets a reference to the given bool and assigns it to the ShowSupportBadge field.
func (o *PurchaseUpdate) SetShowSupportBadge(v bool) {
	o.ShowSupportBadge = &v
}

func (o PurchaseUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PurchaseUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HideBuyButtonUntil) {
		toSerialize["hideBuyButtonUntil"] = o.HideBuyButtonUntil
	}
	if !IsNil(o.ShowSupportBadge) {
		toSerialize["showSupportBadge"] = o.ShowSupportBadge
	}
	return toSerialize, nil
}

type NullablePurchaseUpdate struct {
	value *PurchaseUpdate
	isSet bool
}

func (v NullablePurchaseUpdate) Get() *PurchaseUpdate {
	return v.value
}

func (v *NullablePurchaseUpdate) Set(val *PurchaseUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullablePurchaseUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullablePurchaseUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurchaseUpdate(val *PurchaseUpdate) *NullablePurchaseUpdate {
	return &NullablePurchaseUpdate{value: val, isSet: true}
}

func (v NullablePurchaseUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurchaseUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


