/*
Immich

Immich API

API version: 2.7.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the ServerFeaturesDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerFeaturesDto{}

// ServerFeaturesDto struct for ServerFeaturesDto
type ServerFeaturesDto struct {
	// Whether config file is available
	ConfigFile bool `json:"configFile"`
	// Whether duplicate detection is enabled
	DuplicateDetection bool `json:"duplicateDetection"`
	// Whether email notifications are enabled
	Email bool `json:"email"`
	// Whether facial recognition is enabled
	FacialRecognition bool `json:"facialRecognition"`
	// Whether face import is enabled
	ImportFaces bool `json:"importFaces"`
	// Whether map feature is enabled
	Map bool `json:"map"`
	// Whether OAuth is enabled
	Oauth bool `json:"oauth"`
	// Whether OAuth auto-launch is enabled
	OauthAutoLaunch bool `json:"oauthAutoLaunch"`
	// Whether OCR is enabled
	Ocr bool `json:"ocr"`
	// Whether password login is enabled
	PasswordLogin bool `json:"passwordLogin"`
	// Whether reverse geocoding is enabled
	ReverseGeocoding bool `json:"reverseGeocoding"`
	// Whether search is enabled
	Search bool `json:"search"`
	// Whether sidecar files are supported
	Sidecar bool `json:"sidecar"`
	// Whether smart search is enabled
	SmartSearch bool `json:"smartSearch"`
	// Whether trash feature is enabled
	Trash bool `json:"trash"`
	AdditionalProperties map[string]interface{}
}

type _ServerFeaturesDto ServerFeaturesDto

// NewServerFeaturesDto instantiates a new ServerFeaturesDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerFeaturesDto(configFile bool, duplicateDetection bool, email bool, facialRecognition bool, importFaces bool, map_ bool, oauth bool, oauthAutoLaunch bool, ocr bool, passwordLogin bool, reverseGeocoding bool, search bool, sidecar bool, smartSearch bool, trash bool) *ServerFeaturesDto {
	this := ServerFeaturesDto{}
	this.ConfigFile = configFile
	this.DuplicateDetection = duplicateDetection
	this.Email = email
	this.FacialRecognition = facialRecognition
	this.ImportFaces = importFaces
	this.Map = map_
	this.Oauth = oauth
	this.OauthAutoLaunch = oauthAutoLaunch
	this.Ocr = ocr
	this.PasswordLogin = passwordLogin
	this.ReverseGeocoding = reverseGeocoding
	this.Search = search
	this.Sidecar = sidecar
	this.SmartSearch = smartSearch
	this.Trash = trash
	return &this
}

// NewServerFeaturesDtoWithDefaults instantiates a new ServerFeaturesDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerFeaturesDtoWithDefaults() *ServerFeaturesDto {
	this := ServerFeaturesDto{}
	return &this
}

// GetConfigFile returns the ConfigFile field value
func (o *ServerFeaturesDto) GetConfigFile() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ConfigFile
}

// GetConfigFileOk returns a tuple with the ConfigFile field value
// and a boolean to check if the value has been set.
func (o *ServerFeaturesDto) GetConfigFileOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConfigFile, true
}

// SetConfigFile sets field value
func (o *ServerFeaturesDto) SetConfigFile(v bool) {
	o.ConfigFile = v
}

// GetDuplicateDetection returns the DuplicateDetection field value
func (o *ServerFeaturesDto) GetDuplicateDetection() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DuplicateDetection
}

// GetDuplicateDetectionOk returns a tuple with the DuplicateDetection field value
// and a boolean to check if the value has been set.
func (o *ServerFeaturesDto) GetDuplicateDetectionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DuplicateDetection, true
}

// SetDuplicateDetection sets field value
func (o *ServerFeaturesDto) SetDuplicateDetection(v bool) {
	o.DuplicateDetection = v
}

// GetEmail returns the Email field value
func (o *ServerFeaturesDto) GetEmail() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ServerFeaturesDto) GetEmailOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ServerFeaturesDto) SetEmail(v bool) {
	o.Email = v
}

// GetFacialRecognition returns the FacialRecognition field value
func (o *ServerFeaturesDto) GetFacialRecognition() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FacialRecognition
}

// GetFacialRecognitionOk returns a tuple with the FacialRecognition field value
// and a boolean to check if the value has been set.
func (o *ServerFeaturesDto) GetFacialRecognitionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FacialRecognition, true
}

// SetFacialRecognition sets field value
func (o *ServerFeaturesDto) SetFacialRecognition(v bool) {
	o.FacialRecognition = v
}

// GetImportFaces returns the ImportFaces field value
func (o *ServerFeaturesDto) GetImportFaces() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ImportFaces
}

// GetImportFacesOk returns a tuple with the ImportFaces field value
// and a boolean to check if the value has been set.
func (o *ServerFeaturesDto) GetImportFacesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImportFaces, true
}

// SetImportFaces sets field value
func (o *ServerFeaturesDto) SetImportFaces(v bool) {
	o.ImportFaces = v
}

// GetMap returns the Map field value
func (o *ServerFeaturesDto) GetMap() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Map
}

// GetMapOk returns a tuple with the Map field value
// and a boolean to check if the value has been set.
func (o *ServerFeaturesDto) GetMapOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Map, true
}

// SetMap sets field value
func (o *ServerFeaturesDto) SetMap(v bool) {
	o.Map = v
}

// GetOauth returns the Oauth field value
func (o *ServerFeaturesDto) GetOauth() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Oauth
}

// GetOauthOk returns a tuple with the Oauth field value
// and a boolean to check if the value has been set.
func (o *ServerFeaturesDto) GetOauthOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Oauth, true
}

// SetOauth sets field value
func (o *ServerFeaturesDto) SetOauth(v bool) {
	o.Oauth = v
}

// GetOauthAutoLaunch returns the OauthAutoLaunch field value
func (o *ServerFeaturesDto) GetOauthAutoLaunch() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.OauthAutoLaunch
}

// GetOauthAutoLaunchOk returns a tuple with the OauthAutoLaunch field value
// and a boolean to check if the value has been set.
func (o *ServerFeaturesDto) GetOauthAutoLaunchOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OauthAutoLaunch, true
}

// SetOauthAutoLaunch sets field value
func (o *ServerFeaturesDto) SetOauthAutoLaunch(v bool) {
	o.OauthAutoLaunch = v
}

// GetOcr returns the Ocr field value
func (o *ServerFeaturesDto) GetOcr() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Ocr
}

// GetOcrOk returns a tuple with the Ocr field value
// and a boolean to check if the value has been set.
func (o *ServerFeaturesDto) GetOcrOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ocr, true
}

// SetOcr sets field value
func (o *ServerFeaturesDto) SetOcr(v bool) {
	o.Ocr = v
}

// GetPasswordLogin returns the PasswordLogin field value
func (o *ServerFeaturesDto) GetPasswordLogin() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PasswordLogin
}

// GetPasswordLoginOk returns a tuple with the PasswordLogin field value
// and a boolean to check if the value has been set.
func (o *ServerFeaturesDto) GetPasswordLoginOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PasswordLogin, true
}

// SetPasswordLogin sets field value
func (o *ServerFeaturesDto) SetPasswordLogin(v bool) {
	o.PasswordLogin = v
}

// GetReverseGeocoding returns the ReverseGeocoding field value
func (o *ServerFeaturesDto) GetReverseGeocoding() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ReverseGeocoding
}

// GetReverseGeocodingOk returns a tuple with the ReverseGeocoding field value
// and a boolean to check if the value has been set.
func (o *ServerFeaturesDto) GetReverseGeocodingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReverseGeocoding, true
}

// SetReverseGeocoding sets field value
func (o *ServerFeaturesDto) SetReverseGeocoding(v bool) {
	o.ReverseGeocoding = v
}

// GetSearch returns the Search field value
func (o *ServerFeaturesDto) GetSearch() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Search
}

// GetSearchOk returns a tuple with the Search field value
// and a boolean to check if the value has been set.
func (o *ServerFeaturesDto) GetSearchOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Search, true
}

// SetSearch sets field value
func (o *ServerFeaturesDto) SetSearch(v bool) {
	o.Search = v
}

// GetSidecar returns the Sidecar field value
func (o *ServerFeaturesDto) GetSidecar() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Sidecar
}

// GetSidecarOk returns a tuple with the Sidecar field value
// and a boolean to check if the value has been set.
func (o *ServerFeaturesDto) GetSidecarOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sidecar, true
}

// SetSidecar sets field value
func (o *ServerFeaturesDto) SetSidecar(v bool) {
	o.Sidecar = v
}

// GetSmartSearch returns the SmartSearch field value
func (o *ServerFeaturesDto) GetSmartSearch() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SmartSearch
}

// GetSmartSearchOk returns a tuple with the SmartSearch field value
// and a boolean to check if the value has been set.
func (o *ServerFeaturesDto) GetSmartSearchOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SmartSearch, true
}

// SetSmartSearch sets field value
func (o *ServerFeaturesDto) SetSmartSearch(v bool) {
	o.SmartSearch = v
}

// GetTrash returns the Trash field value
func (o *ServerFeaturesDto) GetTrash() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Trash
}

// GetTrashOk returns a tuple with the Trash field value
// and a boolean to check if the value has been set.
func (o *ServerFeaturesDto) GetTrashOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Trash, true
}

// SetTrash sets field value
func (o *ServerFeaturesDto) SetTrash(v bool) {
	o.Trash = v
}

func (o ServerFeaturesDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerFeaturesDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["configFile"] = o.ConfigFile
	toSerialize["duplicateDetection"] = o.DuplicateDetection
	toSerialize["email"] = o.Email
	toSerialize["facialRecognition"] = o.FacialRecognition
	toSerialize["importFaces"] = o.ImportFaces
	toSerialize["map"] = o.Map
	toSerialize["oauth"] = o.Oauth
	toSerialize["oauthAutoLaunch"] = o.OauthAutoLaunch
	toSerialize["ocr"] = o.Ocr
	toSerialize["passwordLogin"] = o.PasswordLogin
	toSerialize["reverseGeocoding"] = o.ReverseGeocoding
	toSerialize["search"] = o.Search
	toSerialize["sidecar"] = o.Sidecar
	toSerialize["smartSearch"] = o.SmartSearch
	toSerialize["trash"] = o.Trash

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServerFeaturesDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"configFile",
		"duplicateDetection",
		"email",
		"facialRecognition",
		"importFaces",
		"map",
		"oauth",
		"oauthAutoLaunch",
		"ocr",
		"passwordLogin",
		"reverseGeocoding",
		"search",
		"sidecar",
		"smartSearch",
		"trash",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServerFeaturesDto := _ServerFeaturesDto{}

	err = json.Unmarshal(data, &varServerFeaturesDto)

	if err != nil {
		return err
	}

	*o = ServerFeaturesDto(varServerFeaturesDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "configFile")
		delete(additionalProperties, "duplicateDetection")
		delete(additionalProperties, "email")
		delete(additionalProperties, "facialRecognition")
		delete(additionalProperties, "importFaces")
		delete(additionalProperties, "map")
		delete(additionalProperties, "oauth")
		delete(additionalProperties, "oauthAutoLaunch")
		delete(additionalProperties, "ocr")
		delete(additionalProperties, "passwordLogin")
		delete(additionalProperties, "reverseGeocoding")
		delete(additionalProperties, "search")
		delete(additionalProperties, "sidecar")
		delete(additionalProperties, "smartSearch")
		delete(additionalProperties, "trash")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServerFeaturesDto struct {
	value *ServerFeaturesDto
	isSet bool
}

func (v NullableServerFeaturesDto) Get() *ServerFeaturesDto {
	return v.value
}

func (v *NullableServerFeaturesDto) Set(val *ServerFeaturesDto) {
	v.value = val
	v.isSet = true
}

func (v NullableServerFeaturesDto) IsSet() bool {
	return v.isSet
}

func (v *NullableServerFeaturesDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerFeaturesDto(val *ServerFeaturesDto) *NullableServerFeaturesDto {
	return &NullableServerFeaturesDto{value: val, isSet: true}
}

func (v NullableServerFeaturesDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerFeaturesDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


