/*
Immich

Immich API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the WorkflowActionResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowActionResponseDto{}

// WorkflowActionResponseDto struct for WorkflowActionResponseDto
type WorkflowActionResponseDto struct {
	ActionConfig map[string]interface{} `json:"actionConfig"`
	// Action ID
	Id string `json:"id"`
	// Action order
	Order int32 `json:"order"`
	// Plugin action ID
	PluginActionId string `json:"pluginActionId"`
	// Workflow ID
	WorkflowId string `json:"workflowId"`
	AdditionalProperties map[string]interface{}
}

type _WorkflowActionResponseDto WorkflowActionResponseDto

// NewWorkflowActionResponseDto instantiates a new WorkflowActionResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowActionResponseDto(actionConfig map[string]interface{}, id string, order int32, pluginActionId string, workflowId string) *WorkflowActionResponseDto {
	this := WorkflowActionResponseDto{}
	this.ActionConfig = actionConfig
	this.Id = id
	this.Order = order
	this.PluginActionId = pluginActionId
	this.WorkflowId = workflowId
	return &this
}

// NewWorkflowActionResponseDtoWithDefaults instantiates a new WorkflowActionResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowActionResponseDtoWithDefaults() *WorkflowActionResponseDto {
	this := WorkflowActionResponseDto{}
	return &this
}

// GetActionConfig returns the ActionConfig field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *WorkflowActionResponseDto) GetActionConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ActionConfig
}

// GetActionConfigOk returns a tuple with the ActionConfig field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowActionResponseDto) GetActionConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ActionConfig) {
		return map[string]interface{}{}, false
	}
	return o.ActionConfig, true
}

// SetActionConfig sets field value
func (o *WorkflowActionResponseDto) SetActionConfig(v map[string]interface{}) {
	o.ActionConfig = v
}

// GetId returns the Id field value
func (o *WorkflowActionResponseDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WorkflowActionResponseDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WorkflowActionResponseDto) SetId(v string) {
	o.Id = v
}

// GetOrder returns the Order field value
func (o *WorkflowActionResponseDto) GetOrder() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *WorkflowActionResponseDto) GetOrderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Order, true
}

// SetOrder sets field value
func (o *WorkflowActionResponseDto) SetOrder(v int32) {
	o.Order = v
}

// GetPluginActionId returns the PluginActionId field value
func (o *WorkflowActionResponseDto) GetPluginActionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PluginActionId
}

// GetPluginActionIdOk returns a tuple with the PluginActionId field value
// and a boolean to check if the value has been set.
func (o *WorkflowActionResponseDto) GetPluginActionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PluginActionId, true
}

// SetPluginActionId sets field value
func (o *WorkflowActionResponseDto) SetPluginActionId(v string) {
	o.PluginActionId = v
}

// GetWorkflowId returns the WorkflowId field value
func (o *WorkflowActionResponseDto) GetWorkflowId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value
// and a boolean to check if the value has been set.
func (o *WorkflowActionResponseDto) GetWorkflowIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowId, true
}

// SetWorkflowId sets field value
func (o *WorkflowActionResponseDto) SetWorkflowId(v string) {
	o.WorkflowId = v
}

func (o WorkflowActionResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowActionResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ActionConfig != nil {
		toSerialize["actionConfig"] = o.ActionConfig
	}
	toSerialize["id"] = o.Id
	toSerialize["order"] = o.Order
	toSerialize["pluginActionId"] = o.PluginActionId
	toSerialize["workflowId"] = o.WorkflowId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WorkflowActionResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"actionConfig",
		"id",
		"order",
		"pluginActionId",
		"workflowId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowActionResponseDto := _WorkflowActionResponseDto{}

	err = json.Unmarshal(data, &varWorkflowActionResponseDto)

	if err != nil {
		return err
	}

	*o = WorkflowActionResponseDto(varWorkflowActionResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "actionConfig")
		delete(additionalProperties, "id")
		delete(additionalProperties, "order")
		delete(additionalProperties, "pluginActionId")
		delete(additionalProperties, "workflowId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWorkflowActionResponseDto struct {
	value *WorkflowActionResponseDto
	isSet bool
}

func (v NullableWorkflowActionResponseDto) Get() *WorkflowActionResponseDto {
	return v.value
}

func (v *NullableWorkflowActionResponseDto) Set(val *WorkflowActionResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowActionResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowActionResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowActionResponseDto(val *WorkflowActionResponseDto) *NullableWorkflowActionResponseDto {
	return &NullableWorkflowActionResponseDto{value: val, isSet: true}
}

func (v NullableWorkflowActionResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowActionResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


