/*
Immich

Immich API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package immich

import (
	"encoding/json"
	"fmt"
)

// checks if the SyncAlbumUserV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncAlbumUserV1{}

// SyncAlbumUserV1 struct for SyncAlbumUserV1
type SyncAlbumUserV1 struct {
	// Album ID
	AlbumId string `json:"albumId"`
	Role AlbumUserRole `json:"role"`
	// User ID
	UserId string `json:"userId"`
	AdditionalProperties map[string]interface{}
}

type _SyncAlbumUserV1 SyncAlbumUserV1

// NewSyncAlbumUserV1 instantiates a new SyncAlbumUserV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncAlbumUserV1(albumId string, role AlbumUserRole, userId string) *SyncAlbumUserV1 {
	this := SyncAlbumUserV1{}
	this.AlbumId = albumId
	this.Role = role
	this.UserId = userId
	return &this
}

// NewSyncAlbumUserV1WithDefaults instantiates a new SyncAlbumUserV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncAlbumUserV1WithDefaults() *SyncAlbumUserV1 {
	this := SyncAlbumUserV1{}
	return &this
}

// GetAlbumId returns the AlbumId field value
func (o *SyncAlbumUserV1) GetAlbumId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AlbumId
}

// GetAlbumIdOk returns a tuple with the AlbumId field value
// and a boolean to check if the value has been set.
func (o *SyncAlbumUserV1) GetAlbumIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AlbumId, true
}

// SetAlbumId sets field value
func (o *SyncAlbumUserV1) SetAlbumId(v string) {
	o.AlbumId = v
}

// GetRole returns the Role field value
func (o *SyncAlbumUserV1) GetRole() AlbumUserRole {
	if o == nil {
		var ret AlbumUserRole
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *SyncAlbumUserV1) GetRoleOk() (*AlbumUserRole, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *SyncAlbumUserV1) SetRole(v AlbumUserRole) {
	o.Role = v
}

// GetUserId returns the UserId field value
func (o *SyncAlbumUserV1) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *SyncAlbumUserV1) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *SyncAlbumUserV1) SetUserId(v string) {
	o.UserId = v
}

func (o SyncAlbumUserV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncAlbumUserV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["albumId"] = o.AlbumId
	toSerialize["role"] = o.Role
	toSerialize["userId"] = o.UserId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SyncAlbumUserV1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"albumId",
		"role",
		"userId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSyncAlbumUserV1 := _SyncAlbumUserV1{}

	err = json.Unmarshal(data, &varSyncAlbumUserV1)

	if err != nil {
		return err
	}

	*o = SyncAlbumUserV1(varSyncAlbumUserV1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "albumId")
		delete(additionalProperties, "role")
		delete(additionalProperties, "userId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSyncAlbumUserV1 struct {
	value *SyncAlbumUserV1
	isSet bool
}

func (v NullableSyncAlbumUserV1) Get() *SyncAlbumUserV1 {
	return v.value
}

func (v *NullableSyncAlbumUserV1) Set(val *SyncAlbumUserV1) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncAlbumUserV1) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncAlbumUserV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncAlbumUserV1(val *SyncAlbumUserV1) *NullableSyncAlbumUserV1 {
	return &NullableSyncAlbumUserV1{value: val, isSet: true}
}

func (v NullableSyncAlbumUserV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncAlbumUserV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


